### PR TITLE
separate the android project from the make system.

### PR DESCRIPTION
**Pull request by alex19EP**
I made the build of android application independent of make and autoconf.

this simplefies building application on non-linux platforms and improves project usability with android-studio.

### CODE REVIEW

**Comment by alex19EP** [comment]
this pr is ready for merge.

**Comment by valdisvi** [comment]
Can you also update Android dependencies in `docs/building.md` file (including Java 11)?

**Comment by alex19EP** [comment]
done

**Comment by valdisvi** [comment]
Last commit has too many unneeded changes. Please fix that and then looks like it can be merged.

**Comment by alex19EP** [comment]
> Last commit has too many unneeded changes.

hmm. examples?

**Comment by valdisvi** [comment]
I meant about documentation: https://github.com/espeak-ng/espeak-ng/pull/960/commits/0d9e182d1c2ed11b8afb01ca131e5bcac661d6e0

**Comment by valdisvi** [comment]
If you want to improve format (which should be consistent) it should be separate commit, to not be confused with updated dependencies.

**Comment by alex19EP** [comment]
o I see vscode formatted the file

**Comment by alex19EP** [comment]
ok I think all is fine now.

**Comment by valdisvi** [comment]
Thank you for your contribution!

**Pull request merged**
