### PR TITLE
code cleanup: remove chromium extension

### PR DESCRIPTION
**Pull request by djphoenix**
Rationale:

- It is not a part of eSpeak-NG, nor useful wrapper/adapter
- It is not properly documented and maintained
- It is unsafe (running PHP daemon with user privileges and [launch ANY](https://github.com/espeak-ng/espeak-ng/blob/6d7101c03c865c625d6c92b8dda15db0859fe3c2/chromium_extension/index.php#L8) received command via [passthru](https://www.php.net/manual/en/function.passthru.php) - seriously?)

### CODE REVIEW

**Comment by guest271314** [comment]
@djphoenix 

Would have been nice to get a ping on this. We can stream the raw PCM directly from `espeak-ng` to the browser without using a local server or `passthru()`.

**Comment by djphoenix** [comment]
@guest271314 you can avoid native code at all, by using WebAssembly code built with emscripten (that included in espeak codebase).

**Comment by guest271314** [comment]
> Rationale:
> 
> * It is not a part of eSpeak-NG, nor useful wrapper/adapter

The only purpose of the code is to execute eSpeak-NG with the command originating from the browser, with stdout from eSpeak-NG streamed to the browser or written to a file accessible  by browser.

> * It is not properly documented and maintained

Sure it is. Right here: https://github.com/guest271314/native-messaging-espeak-ng 

> * It is unsafe (running PHP daemon with user privileges and [launch ANY](https://github.com/espeak-ng/espeak-ng/blob/6d7101c03c865c625d6c92b8dda15db0859fe3c2/chromium_extension/index.php#L8) received command via [passthru](https://www.php.net/manual/en/function.passthru.php) - seriously?)

You are executing local code in a Native Messaging host on your machine that starts a local server that you are in complete control of. 

There is no "unsafe" involved unless you decide to write a malicious program, then send the command to execute your malicious program to attack yourself.

**Comment by guest271314** [comment]
> @guest271314 you can avoid native code at all, by using WebAssembly code built with emscripten (that included in espeak codebase).

That code does not support SSML input.

**Comment by guest271314** [comment]
> @guest271314 you can avoid native code at all, by using WebAssembly code built with emscripten (that included in espeak codebase).

That code also uses the deprecated Web Audio API `ScriptProcessorNode`.

I really don't see the issue you have with the Native Messaging browser extension.

I can change the approach to write directly from `espeak-ng --stdout` to the browser, bypassing starting a local server altogether; in C, C++, etc.

That's what I do here: https://github.com/guest271314/captureSystemAudio/blob/10908bd48f08018a338aa046a26429189bbcdc7b/native_messaging/capture_system_audio/capture_system_audio.c#L44-L64.

**Comment by guest271314** [comment]
Re

> It is unsafe (running PHP daemon with user privileges and [launch ANY](https://github.com/espeak-ng/espeak-ng/blob/6d7101c03c865c625d6c92b8dda15db0859fe3c2/chromium_extension/index.php#L8) received command via [passthru](https://www.php.net/manual/en/function.passthru.php) - seriously?)

Would you prefer a local HTTPS Deno server where we use a `Set` to make sure we can only execute specific commands?


A local version of this https://github.com/guest271314/native-messaging-espeak-ng/blob/deno-server/deno_server.js where I included provisions specifically for the case of creating a local server that will only execute specific commands - even though we are in control throughout the process locally 
```
const commands = new Set();
commands.add('espeak-ng');
async function main() {
  const responseInit = {
    duplex: 'half',
    keepalive: true,
    headers: {
      'Content-Type': 'application/octet-stream',
      'Cross-Origin-Opener-Policy': 'unsafe-none',
      'Cross-Origin-Embedder-Policy': 'unsafe-none',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Private-Network': 'true',
      'Access-Control-Allow-Headers': 'Access-Control-Request-Private-Network',
      'Access-Control-Allow-Methods': 'OPTIONS,POST,GET,HEAD',
    },
  };
  const controller = new AbortController();
  const {signal} = controller;
  await serveTls(async(request)=>{
    console.log(request.method);
    let body = null;
    if (request.method === 'OPTIONS' || request.method === 'HEAD') {
      return new Response(null,responseInit);
    }
    const text = await request.text();
    const json = text.split(' ');
    if (commands.has(json[0])) {
      const command = new Deno.Command(json.shift(),{
        args: json,
        stdout: 'piped',
        stdin: 'piped',
      });
      const process = command.spawn();
      const reader = process.stdout.getReader();
      body = new ReadableStream({
        async pull(c) {
          const {value, done} = await reader.read();
          if (done) {
            c.close();
          }
          c.enqueue(value);
        },
        async cancel(reason) {
          console.log('cancelled', reason);
          console.log(command, process);
          process.kill('SIGKILL');
          server = null;
          controller = null;
          // Deno.exit(0);
          // await sendMessage(encoder.encode(`"Local server off"`));
        },
      });
    }
    return new Response(body,responseInit);
  }
  , {
    certFile: 'certificate.pem',
    keyFile: 'certificate.key',
    signal,
  });
}
```

Or a Bash Native Messaging host https://github.com/guest271314/native-messaging-espeak-ng/blob/bash-audioworklet/host/native-messaging-host-bash.sh with `espeak-ng` hardcoded where we write a file to the local browser extension directory that we get (using `fetch()` with `"web_accessible_resources"` defined in manifest.json, or File System Access API) in the browser?

```
#!/bin/bash
# Loop forever, to deal with chrome.runtime.connectNative
# https://stackoverflow.com/a/24777120
while IFS= read -r -n1 c; do
    # We do not message input text to Native Messaging host
    # we just message `0` then get input.txt file written by Native File System 
    if [ "$c" == "0" ] ; then
       continue
    fi
    # Output phonemes to Native Messaging application
    message="\"$(espeak-ng -m -x -f input.txt -w output.wav | base64 -w 0)\""
    # Calculate the byte size of the string.
    # NOTE: This assumes that byte length is identical to the string length!
    # Do not use multibyte (unicode) characters, escape them instead, e.g.
    # message='"Some unicode character:\u1234"'
    messagelen=${#message}

    # Convert to an integer in native byte order.
    # If you see an error message in Chrome's stdout with
    # "Native Messaging host tried sending a message that is ... bytes long.",
    # then just swap the order, i.e. messagelen1 <-> messagelen4 and
    # messagelen2 <-> messagelen3
    messagelen1=$(( ($messagelen      ) & 0xFF ))               
    messagelen2=$(( ($messagelen >>  8) & 0xFF ))               
    messagelen3=$(( ($messagelen >> 16) & 0xFF ))               
    messagelen4=$(( ($messagelen >> 24) & 0xFF ))               

    # Print the message byte length followed by the actual message.
    printf "$(printf '\\x%x\\x%x\\x%x\\x%x' \
        $messagelen1 $messagelen2 $messagelen3 $messagelen4)%s" "$message"
done
```

**Comment by guest271314** [comment]
Native Messaging https://github.com/browserext/native-messaging/issues/6 is happening entirely on your own machine. You, the individual end-user, is in complete control of what gets executed and what does not get executed.

I'm just trying to understand your rationale, and what I need to do to address each of your concerns; I think I covered them all in the branches of native-messaging-espeak-ng, if not, kindly advise me of exactly how you think the locally installed or built yet not installed espeak-ng should be executed commanded from the browser.

> @guest271314 you can avoid native code at all, by using WebAssembly code built with emscripten (that included in espeak codebase).

I'm glad you brought that up. I've inquired about that here https://github.com/espeak-ng/espeak-ng/issues/736. Maybe you can implement SSML input in the source code so that code will have that capability like `espeak-ng` does. 

I think I can adjust the front-end code to use `AudioWorklet` or `MediaStreamTrackGenerator` to create a stream from the output WAV.

**Pull request merged**
