### PR TITLE
My languages

### PR DESCRIPTION
**Pull request by Andyvladescu73**

### CODE REVIEW

**Comment by alex19EP** [comment]
stop closing and opening new prs.

**Comment by Andyvladescu73** [comment]
> stop closing and opening new prs.

Sorry, I was doing the Crimean Tatar language and I was about to make a mistake. But when I made a mistake, I did it again, but now I did it very well. Please don't get angry at me when I made mistakes and did it again!

**Comment by alex19EP** [comment]
Please learn how to work with Git and GitHub you don't need to recreate your pull request to fix an error

**Comment by Andyvladescu73** [comment]
> Please learn how to work with Git and GitHub you don't need to recreate your pull request to fix an error

Well, yes, but the others did that language, for example Carmina16. As she did, so I did it with my hands

**Comment by Andyvladescu73** [comment]
I'm sorry, Mr. Alexander! But I can't build from Git. I tried to work with espeak-ng thanks to the Git application and when I installed it, but I don't know anything and I didn't succeed. But once I work from git. A txt file appears and does not give any result. But keep calm! I did nothing but work on Github doing the foreign language, for example Crimean Tatar and that's it. Everyone, that is us, creates this foreign language as usual. I apologize for any inconvenience and we make sure that the Crimean Tatar language appears on the odo.lv espeak-ng testing page. It was understood???

**Pull request closed without merging**
