### PR TITLE
Adding Crimean Tatar language

### PR DESCRIPTION
**Pull request by Andyvladescu73**
Adds initial support for Crimean Tatar

### CODE REVIEW

**Comment by alex19EP** [comment]
please stop opening new prs. or I will ban you.

if you want to work with espeak-ng you need:

1. answer to our comments
2. fix failing tests
3. use git and not github interface to do commits

sorry but if you don't change your behavior, then I'll just ban you again.

**Comment by Andyvladescu73** [comment]
I don't know, how to fixing failing tests... if yes, please help me because I don't know how to solve the failing of the test

**Comment by Andyvladescu73** [comment]
But I can't do anything like that, but the only thing left is to create foreign languages, just like the others did at the same time.

**Comment by alex19EP** [comment]
you can see which tests are failing and then see how other people have fixed them.

**Pull request closed without merging**
