### PR TITLE
Fix OSX compilation

### LINKED ISSUE #12: Support Mac OSX
The main issue here is reworking the event logic to use Mac compatible versions of the `sem_` functions, e.g. via POSIX APIs.

### PR DESCRIPTION
**Pull request by MartinDelille**
This pull request aims to fix #12. The compilation fix for OSX should be quite the same than the one for windows raised #167 

If it compiles fine, I'm not able to synthetise any sentences running: `espeak "Some text"`

There should be a way to make it work because the version on *Homebrew* works fine: https://github.com/Homebrew/homebrew-core/blob/master/Formula/espeak.rb

### CODE REVIEW

**Comment by MartinDelille** [comment]
Note: it works if I export the result to a wave file: `espeak -w file.wav "Some text"`. I will check changing my `configure` option.

**Comment by rhdunn** [comment]
I have pushed a compatibility shim for `endian.h` that should support Mac OSX. If that does not work, fixes should be made to that file, not to the files that include it.

Regarding the audio, you need the `pcaudiolib` library. That library does not currently support Mac OSX's `CoreAudio` APIs, so audio does not currently work with OSX. Patches are welcome.

**Comment by MartinDelille** [comment]
Ok it seems that @ragb start something there: rhdunn/pcaudiolib#4

I compiled and installed the library in this [branch](https://github.com/ragb/pcaudiolib/tree/feature/coreaudio) but it doesn't work better. I'm totally new to automake, is there something to do to use this specific version of pcaudiolib?

**Comment by lajash** [comment]
Hey Martin,
Did you perchance figure out the duplicate symbols issue ? 
Thanks.

**Comment by alex19EP** [comment]
I think now espeak-ng works on macos

**Pull request closed without merging**
