### PR TITLE
Reimplemented .replace rule, unit tests for replacement

### PR DESCRIPTION
**Pull request by valdisvi**

### CODE REVIEW

**Comment by michaelDCurran** [comment]
This now seems to fix #523 for me.

**Comment by zstanecic** [comment]
Hi mick,
can you merge these changes to the NVDDA alpha, so that i can verify it for macedonian?

**Comment by valdisvi** [comment]
You can test updated version on https://odo.lv/Espeak

**Comment by zstanecic** [comment]
Hi Valdis,
are you trying to offend me?
i don't speak Latvian, so i cannot use your page.
If you want to use it, translate it to english.
Thanks,
Zvonimir

**Comment by zstanecic** [comment]
btw, your page is not working with google chrome, i mean the .oga format with built-in player

**Comment by valdisvi** [comment]
By default, English should be opened, if necessary you can switch to it, on **en** link at upper right corner. If your browser doesn't support *.oga directly, you can download file by clicking on link **download sound file**, and may play it with local player directly (if saving file is not necessary).

**Comment by zstanecic** [comment]
ni, the language switching it is not working.
It is better for me to test espeak locally when it is merged into NVDA

**Comment by michaelDCurran** [comment]
@zstanecic: Please test the following NVDA try build:

https://ci.appveyor.com/api/buildjobs/99gn1sj0kx0su7jq/artifacts/output%2Fnvda_snapshot_try-eSpeakFix-15650%2C5b403df7.exe

This contains @valdisvi's fix.

If this works okay for you, and when/if Reece merges this to eSpeak-ng 
master, then  I will look at updating espeak-ng for NVDA master.

**Comment by zstanecic** [comment]
No, unfortunatelly, i cannot say that's a complete fix in espeak.
example: it breaks NVDA spelling:
try to type characters with echo turned on using macedonian voice.
expected behaviour: only character name should be spoken:
behaviour we have now:
we have characters spoken with zeros before and after the character.
for example:
0m0 or 0r0
it should be spoken as respective characters with phonemes.
when pressing numpad 5 two times, synthesizer is not spelling the current word, but it says 0 with the one character and stops.
it doesn't crach, but only stops speaking:
so, cyrillic spelling and reading is broken, but with another output.
@mdcurran,
can you reproduce the same what i am reproducing?
any text or spelling of latin / cyrillic letters will do?

**Comment by michaelDCurran** [comment]
Yes, when speaking characters, I can confirm there is a 0m being spoken 
before each character.
And I can also confirm it stops after spelling the first character of a 
word in NVDA.
To be clear though, it has fixed the other original issue of the junk at 
the end of strings.
However, if I compile eSpeak-ng for Windows, and I provide the following 
xml, I get an assertion error:
<say-as interpret-as="characters">mh</say-as>
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...programming\git\espeak-ng\src\windows\x64\Debug\espeak-ng.exe
File: minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp
Line: 42

Expression: c >= -1 && c <= 255

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore
---------------------------

**Comment by michaelDCurran** [comment]
Looks like the assertion was in a call to isupper.

Here is a stack dump for the assertion above:
```
 # Child-SP          RetAddr           Call Site
00 000000ff`e754b0b0 00007ff8`1819eef7 ucrtbased!_chvalidator_l(struct __crt_locale_pointers * locale = 0x000000ff`e754b150, int c = 0n-47, int mask = 0n1)+0x5a [minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp @ 42] 
01 000000ff`e754b120 00007ff8`1819f2cf ucrtbased!_isupper_l(int c = 0n-47, struct __crt_locale_pointers * locale = 0x00000000`00000000)+0x37 [minkernel\crts\ucrt\src\appcrt\convert\_ctype.cpp @ 46] 
02 000000ff`e754b180 00007ff8`18885d0b ucrtbased!isupper(int c = 0n-47)+0x1f [minkernel\crts\ucrt\src\appcrt\convert\_ctype.cpp @ 51] 
03 000000ff`e754b1c0 00007ff8`188869bf libespeak_ng!ReplaceMatchingChars(char ** matchstart = 0x000000ff`e754b778, char * charto = 0x000000ff`e754b970 "???", int usedfrom = 0n1, int usedto = 0n2)+0xbb [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\translate.c @ 1839] 
04 000000ff`e754b750 00007ff8`18887218 libespeak_ng!TranslateChars(struct Translator * tr = 0x0000024a`f135d8d0, char * source = 0x00007ff8`188fc400 " ???")+0x29f [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\translate.c @ 1937] 
05 000000ff`e754bc90 00007ff8`1888272a libespeak_ng!TranslateClause(struct Translator * tr = 0x0000024a`f135d8d0, int * tone_out = 0x000000ff`e754e4a4, char ** voice_change = 0x000000ff`e754e4c8)+0x6b8 [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\translate.c @ 2197] 
06 000000ff`e754e480 00007ff8`18874176 libespeak_ng!SpeakNextClause(int control = 0n0)+0x9a [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\synthesize.c @ 1568] 
07 000000ff`e754e5e0 00007ff8`18875e7a libespeak_ng!Synthesize(unsigned int unique_identifier = 0, void * text = 0x0000024a`f127ee2e, int flags = 0n4368)+0x116 [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\speech.c @ 456] 
08 000000ff`e754e760 00007ff8`188757a5 libespeak_ng!sync_espeak_Synth(unsigned int unique_identifier = 0, void * text = 0x0000024a`f127ee2e, unsigned int position = 0, espeak_POSITION_TYPE position_type = POS_CHARACTER (0n1), unsigned int end_position = 0, unsigned int flags = 0x1110, void * user_data = 0x00000000`00000000)+0x13a [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\speech.c @ 566] 
09 000000ff`e754e8c0 00007ff8`1885a5b6 libespeak_ng!espeak_ng_Synthesize(void * text = 0x0000024a`f127ee2e, unsigned int64 size = 0x2e, unsigned int position = 0, espeak_POSITION_TYPE position_type = POS_CHARACTER (0n1), unsigned int end_position = 0, unsigned int flags = 0x1110, unsigned int * unique_identifier = 0x00007ff8`188f8c34, void * user_data = 0x00000000`00000000)+0xe5 [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\speech.c @ 703] 
0a 000000ff`e754e9e0 00007ff6`be634f96 libespeak_ng!espeak_Synth(void * text = 0x0000024a`f127ee2e, unsigned int64 size = 0x2e, unsigned int position = 0, espeak_POSITION_TYPE position_type = POS_CHARACTER (0n1), unsigned int end_position = 0, unsigned int flags = 0x1110, unsigned int * unique_identifier = 0x00000000`00000000, void * user_data = 0x00000000`00000000)+0x86 [c:\users\mick\programming\git\espeak-ng\src\libespeak-ng\espeak_api.c @ 93] 
0b 000000ff`e754eb00 00007ff6`be636ab4 espeak_ng!main(int argc = 0n7, char ** argv = 0x0000024a`f127ed90)+0xfc6 [c:\users\mick\programming\git\espeak-ng\src\espeak-ng.c @ 681] 
0c 000000ff`e754f830 00007ff6`be636964 espeak_ng!invoke_main(void)+0x34 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 79] 
0d 000000ff`e754f870 00007ff6`be63682e espeak_ng!__scrt_common_main_seh(void)+0x124 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
0e 000000ff`e754f8d0 00007ff6`be636b49 espeak_ng!__scrt_common_main(void)+0xe [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 326] 
0f 000000ff`e754f900 00007ff8`70e23704 espeak_ng!mainCRTStartup(void)+0x9 [f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
10 000000ff`e754f930 00007ff8`7336a1d1 KERNEL32!BaseThreadInitThunk+0x14
11 000000ff`e754f960 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by valdisvi** [comment]
If I do:
```
espeak-ng -vmk -X
```
and then enter characters one by one, it works as expected:
```
b
Replace   b > б
Found: 'б' [b@]  
 b'@
б
Found: 'б' [b@]  
 b'@
```
So, it looks Windows related problem, which I cannot test.

**Comment by rhdunn** [comment]
Hi valdis,
1.  I already have replacement rule tests in `tests/language-replace.test`.
1.  I have reverted the current replace logic to the old logic, keeping the new tests.
1.  I have modified the dictionary format so that it now stores the replacement strings as UTF8, and use `utf8_in` to read those characters.

That is as far as I have gotten.

I prefer this representation, as the UTF8 strings don't have endian issues, and can support full UTF32 codepoints. This allows for replacement rules mapping Fraktur (Latf), Gaelic script (Latg), Ogham, etc. to Latin, and other mappings.

I'm still evaluating whether the location you moved the substitutions to is the best place for it. I haven't yet studied what the code around the `SubstituteChar` call is doing, how it works with `FLAG_CHAR_REPLACED`, etc.. My concern with the new location is what code is no longer called, and what data buffers it is operating on.

**Comment by valdisvi** [comment]
OK

**Pull request closed without merging**
