### PR TITLE
fix 492

### PR DESCRIPTION
**Pull request by hozosch**

### CODE REVIEW

**Comment by hozosch** [comment]
Why don't I see the travis build results?

**Comment by valdisvi** [comment]
Because build is failing. When you change phoneme definitions you also have to update hashsum for phoneme tests in `tests/langugage-phonemes.test` file. In this particular case: 
from `d05d865062b8d9d4b799358f2a912033b05cac28` to `e20faa2bced0d5d6e56bc898dd12eaa75c3d2217`

**Comment by hozosch** [comment]
Well thanks for that info. Now I also see what I was after in my comment. What I meant is that I didn't see the results at all, no matter if they failed or succeded, so couldn't retrieve the hashsum which is what I was looking for. Now, it's there, and no, I don't mean your comment.

**Comment by valdisvi** [comment]
@hozosch, I merged this pull request with [slight change](https://github.com/valdisvi/espeak-ng/commit/21683e0d0e3d351698fd6c69571b04333cad35b7) — I changed your comment `fix 492` to `Fix issue #492` (note hash before number). This change may require you to overwrite history of local repository with history from the main espeak-ng repository.
When mention issues, please use that format, because in that way GitHub automatically generates link to the issue.
Because of your question about build failure I noticed, that Travis builds were failing because of incorrect MBROLA test, which I [fixed](https://github.com/espeak-ng/espeak-ng/commit/cef02afc59da3ad7032d18eae9c807aab3cf93c4).

**Comment by hozosch** [comment]
How do I go about changing the history?

**Comment by valdisvi** [comment]
If you use project on odo.lv, then just choose task **pull from upstream**.

**Comment by hozosch** [comment]
Ah yes, you meant that. Yes, already pushed to my project.

**Pull request closed without merging**
