### PR TITLE
Add Tolkien’s Elvish languages

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
This adds support for [Quenya](https://en.wikipedia.org/wiki/Quenya) and [Sindarin](https://en.wikipedia.org/wiki/Sindarin), the two main Elvish languages invented by J. R . R. Tolkien, to eSpeak NG. (He also developed several other languages to various degrees of completion, but I reckon Quenya and Sindarin are the only ones worth adding to eSpeak NG.) Spelling and stress for both languages are fairly regular, and I hope to have represented them with fair accuracy; in particular, the tests in `tests/language-pronunciation.test` include all the test cases of my [Tolkien Stress Analyser](https://github.com/lucaswerkmeister/tolkien-stress/) ([test source](https://github.com/lucaswerkmeister/tolkien-stress/blob/gh-pages/test/index.test.mjs)), to ensure accurate positioning of the primary stress. (I’m letting eSpeak NG determine the secondary stress automatically – i.e., `espeak-ng-data/lang/art/qya` and `/sjn` don’t define the `S_NO_AUTO_2` flag – and so far I’ve been happy with the results.)

The main source for the pronunciation rules is Appendix E of The Lord of the Rings (the only online copy I’ve found so far is [this PDF](https://portal.tolkienianos.pt/files/The_LotR_IV.pdf), starting on page 82); the [Ambar Eldaron Quenya Dictionary](https://ambar-eldaron.com/telechargements/quenya-engl-A4.pdf) and the [Omikhleia Sindarin Dictionary](https://www.jrrvf.com/hisweloke/sindar/index.html) have also been very useful (though the latter pronounces ⟨i⟩ in the texts as /i/, whereas I believe it should be /ɪ/). Some other resources, and various other notes, are included in the commit messages.

I only have one TODO left that I haven’t been able to fully resolve: the sequence ⟨rh⟩ (Sindarin) or ⟨hr⟩ (Quenya) is supposed to represent “a voiceless _r_” according to Appendix E, which I believe means the [voiceless alveolar trill](https://en.wikipedia.org/wiki/Voiceless_alveolar_trill), IPA /r̥/. I was unable to find a way to make `espeak-ng --ipa` print that character while retaining the correct sound (see commit a39b6b70792b4c8bb4a3467464c9519aa3dc7484), so for now the IPA output for that is /hr/.

I’m hoping you’ll consider merging this (since I noticed there’s already at least one fictional language, Klingon, in the `art` family), but I won’t mind if you decline it either. (I was hoping to compile this into a website in order to offer online Elvish text-to-speech, for which I don’t really need this to be merged; however, I can’t get the emscripten build to work at the moment.)

### CODE REVIEW

**Comment by jaacoppi** [comment]
Excellent work, thank you!

**Comment by Flameborn** [comment]
First of all, thank you very much for adding this.

> ... the latter pronounces ⟨i⟩ in the texts as /i/, whereas I believe it should be /ɪ/).

The consensus is that the vowel *i* is pronounced as in *hit* or *sick*, however, there are some exceptions. Word-initial *i* is usually a /j/, this is the same as in compound names, such as Dóriath ˈdorjaθ, except in shorter words, like *im*.

But there are further exceptions, for example *Minastirith* is usually pronounced as having short /ɪ/ vowels, but the *i* in *tirith* is closer to what's in Fingon /ˈfiŋɡon/ (revised from Finweg, from the Quenya Findekáno).

Where applicable, I would add suggested changes from Neo-Sindarin, a great source is *A Fan's Guide to Neo-Sindarin* by Fiona Jallings or loosely from *A Gateway to Sindarin* (though a bit dated, and not exactly Neo-Sindarin) by David Salo. Although Neo-Sindarin is a bit more liberal, it tries to unify some things that weren't in Tolkien's works and notes. But of course this is up to you.

**Comment by Flameborn** [comment]
@king-dahmanus Feel free to open an issue regarding Klingon, even if you are not sure how to implement fixes, someone might take it up and send a PR. Having an issue explaining what problems you're facing is definitely going to be helpful in the end.

**Comment by valdisvi** [comment]
There is no phoneme `hR` defined in espeak-ng. Therefore what actually happening is `hR` is pronunciated as two following phonemes `h` and `R`, which in IPA are shown as `h` and `r`. You can define new phoneme as sequence of two existing ones and assign `r̥` IPA name to it, if necessary. See more at [Phoneme tables](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md).

**Comment by lucaswerkmeister** [comment]
> You can define new phoneme as sequence of two existing ones and assign `r̥` IPA name to it, if necessary. See more at [Phoneme tables](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md).

Thanks, but how do I define a sequence of two phonemes? I couldn’t figure it out. I tried two `CALL`s now –

```diff
diff --git a/dictsource/qya_rules b/dictsource/qya_rules
index 2ac2bbec..7133447f 100644
--- a/dictsource/qya_rules
+++ b/dictsource/qya_rules
@@ -77,7 +77,7 @@
 	L02) ht	Ct
 	L03) ht	xt
 	hl	l#
-	hr	hR
+	hr	R#
 	hw	w#
 	hy	C
 
diff --git a/phsource/ph_quenya b/phsource/ph_quenya
index 6a2c7374..8b9d5cdf 100644
--- a/phsource/ph_quenya
+++ b/phsource/ph_quenya
@@ -11,6 +11,12 @@ phoneme O
   FMT(vowel/oo)
 endphoneme
 
+phoneme R#
+  ipa r̥
+  CALL base1/h
+  CALL base1/R
+endphoneme
+
 phoneme w#
   vls glt apr  // [h]
   ipa ʍ
```

– but it just sounds identical to `h`, I don’t hear any trace of the `R`. (Two `import_phoneme`s gives a build error.)

**Pull request merged**
