### PR TITLE
Add Shan Language (sh)

### PR DESCRIPTION
**Pull request by ronaldaug**
Shan(Tai) Language
Language name :  **Shan(Tai)**
Language code : **sh**
Wiki : [Shan Language](https://en.wikipedia.org/wiki/Shan_language)
> Actually, we are very new to this kind of TTS technology and need to learn how phoneme table works.
> But please consider adding Shan language in espeak-ng, Thanks in advance. 
> - Shan Developers

### CODE REVIEW

**Comment by rhdunn** [comment]
Thanks for working on this. I have pushed the changes to a `shan` branch, where I am applying various fixes to the language definitions. Regarding the phoneme errors:
1.  Is `2` meant to be the low tone as described in https://en.wikipedia.org/wiki/Shan_language#Tones?
1.  What is `7` meant to be? According to https://en.wikipedia.org/wiki/Shan_language#Tones, there are only 6 tones.
1.  What is `y` meant to be? Is it the `ယ` sound?

**Comment by ronaldaug** [comment]
1. Yes 
2. Shan is a tonal language and we only has 6 different tones.
3. As each letter has an inherent vowel **a** ,  `ya` is the `ယ` sound and **ipa** = /ja/
I have record some audio files and made a page for you [here](https://ronaldaug.ml/shan/), but the audio quality is not really good.

And there is a [shan dictionary here](http://sealang.net/shan/dictionary.htm) which includes **ipa** symbols.

For now I can just reply you from my knowledge, and later then I will collaborate with Shan language research team for a better voices.

**Comment by rhdunn** [comment]
Hi,

I have made various fixes to the phoneme and dictionary files so they now build properly. I have also removed the English-specific definitions, defined the language as a tonal language with the Shan tone definitions, and enabled number processing (so `12`, etc. work).

__NOTE:__ I have removed the `7` tone from the definition of `g` -- should this be tone 6 instead?

I have some more questions:

1.  The `O@` phoneme is used in the definition of `0`. This is used in English for `or` words like `north`; the replacement is `O` for the IPA `ɔ`. Wiktionary (https://en.wiktionary.org/wiki/%E1%80%9E%E1%80%B0%E1%81%BC%E1%80%BA#Shan) and the Shan dictionary you referenced specifies it as `son` instead of `suO@n` (`sɔn`). Looking at the etymology in Wiktionary, the word incorporates the `u` sound in the Lao, Thai, and Chinese derivations of the word. This would be consistent with either a Northern (Lashio, Burma) dialect containing Chinese influences, or an Eastern (Kengtung, Burma) dialect (containing Northern Tai and Lao influences). Thus, preserving the `u` sound, the more accurate transcription would be `suon1`. Is that correct?
1. The `A@` phoneme is used in the definition of `3`. This is used in English for `ar` words like `start`; the replacement is `A:`.
1.  The `A:` phoneme is used for the IPA `a:`. Is this a result of basing the Shan language on English? Does the English `A:` or `a:` sound better? (NOTE: I can set the definition to whichever sounds better, so `a` and `a:` can be used in the rules and list files.)
1.  The `oU` phoneme is used in the definition of `6` instead of `o`. Is this intentional, or due to not having the correct definition of `o`?
1.  The `0` phoneme is used instead of `O` in the definitions of `2` and `12`. Is this intentional? If so, does `0` or `O` sound better for IPA `ɔ`?

**Comment by rhdunn** [comment]
These changes are on the `shan` branch.

**Comment by ronaldaug** [comment]
Please check your email, msclrhd@gmail.com.
 
Actually, I've listen all the sounds from espeak-ng CLI and pick up the closest pronunciations.
So, some of them are not accreted at all. 

1. Yes, it would be consistent with either Chinese or Thai influences. As I speak **Tai Lone** accent ( which is a major accent being used in a middle part of Shan state). Most of us don’t use the **u**. I prefer without **u** sound.

There is an exception, although **သုၼ်** and **သူၼ်** has the different meaning, they pronounces the same `/son1/`.
သုၼ် = 0  
သူၼ် = enclosure
Here, the exception is for the word **သုၼ်** and it only uses when pronounce `0`.  
The default  `သုၼ်` should pronounce as `/sun/` .

2. Yes, you can replace with A: , it is quite similar with the word **arm** /ɑːm/ ( Only the tone is 1 `/sA:m1/` )

3. It’s up to you. For me I prefer `A:`      :D
4. From my listening, `o` is a short sound and `oU` is a bit longer, if it's possible I want to use `oU`. 
5. IPA `ɔ` is the correct one. (I thought it was `0` but when I check it on IPA, it’s an open-mid sound.) 

@rhdunn, Thank you for your time.

**Comment by rhdunn** [comment]
Hi, I have built a definition for Shan separate from your initial commits in the `shan-language` branch:
1.  The vowels and diphthongs are mostly derived from the definitions in the Chinese (Mandarin and Cantonese), and Vietnamese phoneme files.
1.  The phoneme file supports the aspirated and unaspirated plosives, the vowels and diphthongs, and tones of the Shan language.
1.  The rules file has definitions for the Shan consonants. I'm not sure how best to handle the combining characters used for vowels (if I understand correctly how they work) and for the tones.
1.  The list file has definitions for the Shan cardinal numbers from 0 to 99 (I'm not sure how they are written in Shan). These are based on the entries in Wiktionary, and are likely missing entries for 32, 41, 51, etc..

I have used the information in Wikipedia as the basis for this. You can use this as the basis for improving the language definition and rules.

**Comment by ronaldaug** [comment]
@rhdunn, I really appreciate your support and the addition of some basic rules.

1., 2. Now I can understand how things work and I will use these rules for later reference.
3. - I can add the vowel combinations for the rest. (Some are a bit similar to Burmese)
4. - Yes, all the Shan words you have added are correct.

Everything works fine except for the 6 tones. For that I think I have to play with them to get a better sound.

One question.
When I type 12 (e.g twelve), it doesn't pronounce as **twelve**, but it pronounces separately as 1 and 2. What should I do to get a single pronunciation like twelve?

**Comment by rhdunn** [comment]
Re: pronunciation of twelve, etc. you need to compile the espeak binary on that branch. The same applies to getting the tones to work. This is due to the changes to `tr_languages.c`.

**Comment by ronaldaug** [comment]
Thanks again, I think I discovered why tone doesn't work.
I am using `espeak`  which was installed via brew. 
because `espeak-ng` audio doesn't work on Mac. 
I've already read this [Issue](https://github.com/espeak-ng/espeak-ng/issues/12) but it doesn't seem to achieve it in a simple way. 
I think borrowing my friend window laptop is the best option now. 😄

**Comment by ronaldaug** [comment]
1 -  [Line-86](https://github.com/ronaldaug/espeak-ng/blob/6ce702aa8cc42e48de24053678875d94e95592bd/dictsource/shn_rules#L86)  There is a strange `ေႃ` vowel which is a combining of two vowels `ေ` and `ႃ`. 
Here, can I make this `ေႃ` to pronounce as one vowel?
Actually, It has to be like ipa =`ɔ` but currently, it pronounces as two vowels `ei` and `a`.

2 - What should I do to avoid **Wrong initial letters** letter?

3 - What tool you usually use to edit language **rules** and **lists**. I saw **espeakedit** but I haven't tried it yet. Does it compatible with current espeak-ng? 

I don't know why this has a conflict with **de_rules**. 
Thanks in advance.

**Comment by valdisvi** [comment]
You can edit `shn_list` and `shn_rules` files with any text editor you like. You can even edit them in github on-line editor, but editor should handle characters, which doesn't take space on screen.
I use gvim (espeak-ng has [syntax highlighting rules for vim](https://github.com/espeak-ng/espeak-ng/tree/master/vim)) with [unicode.vim plugin](https://www.vim.org/scripts/script.php?script_id=2822).
[Line 86](https://github.com/ronaldaug/espeak-ng/blob/6ce702aa8cc42e48de24053678875d94e95592bd/dictsource/shn_rules#L86) probably should have only one symbol, e.g. single Myanmar e:
```

.group  ေ
      ေ    o // default rule without other characters
              // in group with other characters if necessary
```

**Comment by valdisvi** [comment]
Ronaldaug,
probably merge conflicts come from [this very bad merge commit](https://github.com/ronaldaug/espeak-ng/commit/a1086baf1c6b006ec12a067233ab73821b80421b) in your project, where bunch of files have unnecessary changed permissions.
I couldn't fix git history, therefore I just compared two projects and [applied differences](https://github.com/valdisvi/espeak-ng/commit/789d820ad483ede1294265da0c04b780abedaad5) from your project to main project.
_Please wait, while Reece will merge this into main espeak-ng project._
Then rewrite its history from espeak-ng project. Depending on your preferences, you can do it locally on your computer with commands in your project:
```
git add upstream https://github.com/espeak-ng/espeak-ng.git
git fetch upstream; git reset --hard upstream/master; git clean -fd; git pull upstream master
git push -f origin master
```
Or, in [odo.lv/Espeak](https://odo.lv/Espeak) run tasks:
1. **setup...**
2. **push to origin...**

**Comment by valdisvi** [comment]
Ronaldaug, Reece has merged our changes in espeak-ng.
Please update your project as described above.
Good luck!

**Comment by ronaldaug** [comment]
Thanks for reminding me. I did it on my computer.

**Comment by ronaldaug** [comment]
Hi @valdisvi ,

I show this to some of my Shan friends and they were really impressive.

But, there is an error at [https://odo.lv/Espeak](https://odo.lv/Espeak) 
The error sound is like 

``_:(en)mj'A:1nmA@1(shn)l'e1t@1_|n'E3N_|s'o1n_|s'a:1m_|p'E2t_:``

screen shot 2018-06-02 at 12 35 49 pm

I think it's a conflict with Myanmar letters.
There are 9 consonants that both Shan and Myanmar uses the same, the written styles are the same but the pronunciations are different. 

They are `ၵ  သ တ ထ ပ မ ယ လ ဝ` .

Whenever I include one of these words in my typing, it print out the above error.
It only happens on  [https://odo.lv/Espeak](https://odo.lv/Espeak). 

I've tried on my computer, both Mac and Window. There is no error.
 
Thanks for helping.

**Comment by valdisvi** [comment]
In general, characters are spelled by name, if there is no pronunciation entry for it in `xx_rules` file. I made [additions for this](https://github.com/valdisvi/espeak-ng/commit/ba46ae15c9b192d792d1b73e48f037722dd56343), which you can review and improve. I also recompiled my project on [odo.lv/Espeak](https://odo.lv/Espeak) to the latest version.

**Pull request closed without merging**
