### PR TITLE
ES: improvements for Spanish language

### PR DESCRIPTION
**Pull request by Christianlm**
Created spanish diphthongs [oi], added statements to distinguish final diphtong, Created file phoneme 'oo_' unstressed final vowel.

Replace upercase O in ditc source.

Added statements for unstressed vowels, change length/amplitude for unstressed vowels.

improved spanish prosody in tr_language.c.

Added rule for suffix mente in es_rules.

Translated language names.

Added rules for letter spanish ce cedilla, see issue 130.

Intonation: improved head and prehead in tune q6.

### CODE REVIEW

**Comment by Christianlm** [comment]
Is there any problem to merge this pull request? Thanks.

**Comment by rhdunn** [comment]
No, just been busy with other things.

**Comment by Christianlm** [comment]
Ah ok, sorry. I had a doubt because I used only one commit with multiple comments for all changes. Thanks for your reply.

**Comment by rhdunn** [comment]
I generally prefer separate commits for each change, as it makes tracking down issues easier. For language improvements, it is ok to have multiple changes for a single language in a single commit.

My main requirements are that the commit is self-contained and have a description that describes the changes being made.

**Pull request merged**
