### PR TITLE
Add new variants in favour of #1649

### PR DESCRIPTION
**Pull request by hozosch**
I'm sorry, I didn't know it would detect all variants as changed, I hope it's ok like this. If this pull request is doing any harm, please let me know. I don't see any harm in adding these variants as long as they're handed in the correct way.

### CODE REVIEW

**Comment by hozosch** [comment]
Again, I'm sorry, I don't know how to fix the checks. There is one successful one and the rest failed, but I don't know what to do here.

**Comment by jaacoppi** [comment]
Increasing  N_VOICES_LIST passes `make check`. Probably passes other CI tests as well.

The current value seems arbitrary so it could be changed easily. If we simply increase the value, this same problem will occur later. Should we try to find a better solution by dynamically setting the array size?

**Comment by hozosch** [comment]
Hmm, don't know about that, but I think I kind of understand. So some file must be changed? Don't know how you would make that array dynamic, but if we don't want that problem coming up any longer, this sounds to me as the right solution.

**Comment by gregodejesus** [comment]
Hey. I think this should solve the problems of eSpeak ng when more than 200 variants are added, remove some duplicates so that they do not enter into conflicts with the languages. Here I will share a package with the necessary variants to be added.
without further ado, make the package from here
[!v.zip](https://github.com/espeak-ng/espeak-ng/files/11631959/v.zip)

**Comment by gregodejesus** [comment]
Hey. I will share the last variant to be added, I think this is the closest thing to dectalk's paul, replacing eSpeak's paul. Without further ado, here goes
[paul.zip](https://github.com/espeak-ng/espeak-ng/files/11713266/paul.zip)

**Comment by gregodejesus** [comment]
[muchas variantes actualizadas.zip](https://github.com/espeak-ng/espeak-ng/files/12883936/muchas.variantes.actualizadas.zip)

**Pull request closed without merging**
