### PR TITLE
Add ng API to enable phoneme events

### LINKED ISSUE #1387: Phoneme events are unaccessible with _ng API
`option_phoneme_events` can be set only with call to legacy `espeak_Initialize` method.
Maybe we need to introduce new API for enabling `espeakEVENT_PHONEME`.

### PR DESCRIPTION
**Pull request by djphoenix**
Fixes #1387.
Comments are welcome.

### CODE REVIEW

**Comment by jaacoppi** [comment]
Please provide a test for the functionality. The API is poorly documented and tested so we need more tests.

**Comment by djphoenix** [comment]
> Please provide a test for the functionality.

OK, I will add it soon.

**Comment by alex19EP** [comment]
@djphoenix friendly ping. what's the status of this pr?

**Comment by kirill-jjj** [comment]
@djphoenix, thank you for this pr, as far as I understood it will make it easier for me to debug the Russian language

**Comment by djphoenix** [comment]
@jaacoppi @alex19EP sorry for delay. I have wrote some of test cases, seems to work. Let it pass CI.

**Comment by djphoenix** [comment]
Hmm, seems like `make check` does not invoke `api.test` on CI. But only builds it. @jaacoppi @sthibaul can you review that issue? I'm not sure, but it seems that it is because `api.test` is built _after_ the list of tests have enumerated (see around Makefile.am:L324)

**Comment by sthibaul** [comment]
Indeed, and that's the same for all other compiled tests.  They need to be added to `TEST` by hand. Using `$(check_PROGRAMS)` would probably be convenient for that.

**Comment by sthibaul** [comment]
So something like https://github.com/espeak-ng/espeak-ng/pull/1443 , let's see that it properly runs the tests

**Comment by djphoenix** [comment]
@sthibaul great, seems like it passing. I will rebase my changes on master as #1443 merged.

**Comment by djphoenix** [comment]
@sthibaul seems like failure is not related to my code… but I’m not sure to what.

**Comment by sthibaul** [comment]
That was indeed fishy, you can now try to rebase onto your fix.

**Pull request merged**
