### PR TITLE
Add usan CI run

### PR DESCRIPTION
**Pull request by sthibaul**
Now that all usan errors are fixed.

Ref #220

### CODE REVIEW

**Comment by jaacoppi** [comment]
Hi,

You've done a lot of work all around the code base. Thanks! I'm away until the weekend. I'll check & merge this later if no one else does it before.

Do you think the current tests are enough or should we add more?

**Comment by sthibaul** [comment]
More tests is always welcome, diversity always help finding bugs :)

I  have a group of students who is working on adding more fuzzing, to aim for coverage, systematize testing all voices&variants, etc.

**Comment by sthibaul** [comment]
Oops, sorry, I made it "ready for review" by accident. This depends on the various fix PR

**Comment by sthibaul** [comment]
this depends on pull requests https://github.com/espeak-ng/espeak-ng/pull/1093 https://github.com/espeak-ng/espeak-ng/pull/1094 https://github.com/espeak-ng/espeak-ng/pull/1095 https://github.com/espeak-ng/espeak-ng/pull/1102 https://github.com/espeak-ng/espeak-ng/pull/1103 https://github.com/espeak-ng/espeak-ng/pull/1104 before we can merge it

**Pull request merged**
