### PR TITLE
Do not create audio out if not required

### PR DESCRIPTION
**Pull request by djphoenix**

### CODE REVIEW

**Comment by djphoenix** [comment]
The short story of this patch:
Trying to use library in multiple threads with dlmopen(LM_ID_NEWLM, ...)
But unnecessary calls to pcaudiolib ruins the world (segfaults, SIGBUS, ...)
The first attempt was to build espeak-ng without pcaudiolib, but it breaks audio output at all
So finally I have to realize what is my_audio and see it isn't used without SPEAK_AUDIO flag (and safe to skip initialization)

**Comment by valdisvi** [comment]
@djphoenix, to understand need of your changes, can you put relevant part of your pull request description in the commit message, and also add description/meaning of my_audio variable  in the code? I'm not sure your condition check is written in most intuitive way. E.g. why need to concatenate bits of variables, instead of checking them for specific values with grouped and's?

**Comment by sthibaul** [comment]
> E.g. why need to concatenate bits of variables, instead of checking them for specific values with grouped and's?

You mean this bit
`(my_mode & ENOUTPUT_MODE_SPEAK_AUDIO) == ENOUTPUT_MODE_SPEAK_AUDIO`
? This is done so in all the rest of the code

**Comment by valdisvi** [comment]
Yes. To me it looks very old/school bit-oriented, but if it is so everywhere else, may be the same for consistency.

**Comment by djphoenix** [comment]
> Yes. To me it looks very old/school bit-oriented, but if it is so everywhere else, may be the same for consistency.

Yes, I just follow project codestyle.

**Comment by djphoenix** [comment]
> can you put relevant part of your pull request description in the commit message, and also add description/meaning of my_audio variable in the code?

I'm not sure what to add in code. The commit changes the single thing that mentioned in message: audio object is not needed without ENOUTPUT_MODE_SPEAK_AUDIO flag.

**Comment by djphoenix** [comment]
Guys, does anything block it from landing? I can fix it too, but I need to know what)

**Comment by alex19EP** [comment]
I just don't understand it at all. and waiting for my smarter colleagues.

**Comment by alex19EP** [comment]
ok since all checks passed and no one protested i just yolo merge it tomorrow.

**Pull request merged**
