### PR TITLE
fix #1370 Cmn voice not correctly translated

### LINKED ISSUE #1370: Cmn voice not correctly translated
@jaacoppi

This is a following issue of #1044.

I apologize for my not careful test. I find issues after @cary-rowen tell me that there are still problems with Chinese Mandarin voice.

Here is the current voice output:
```
$ espeak-ng -x -vcmn '此电脑 means this computer'
c'i3_| di11'a4n_| na11'o3_| (en)mi:11nz_| DI11s_| k@11mpju:11t311(cmn)_|
```

And following output from older version is much better than current situation:
```
tsh'i[21_| t'iE51n_| n'Au21_| (en)mi:44nz_| DI11s_| k@11mpju:11t311(cmn)_|
```

Maybe this is why you had comment: https://github.com/espeak-ng/espeak-ng/issues/1044#issuecomment-993829386

Here is the revert code:
[cmn_revert.patch.txt](https://github.com/espeak-ng/espeak-ng/files/9554581/cmn_revert.patch.txt)

In fact, it's a temporary solution of #1163 .

I will try to compare the rules of Cantonese and Mandarin to find whether there are clues to make both Mandarin and English read correctly.

### PR DESCRIPTION
**Pull request by hgneng**
1. Rewrite cmn_rules. Vowel will be spoken as Mandarin only when it's with a tone number. Otherwise, it will be regarded as English. This will make English words translated more correctly.
2. Fix issue of word item in cmn_listx not taking effect.
3. Fix dictionary_skipwords bug. It should be injected when re-structing method TranslateWord3.

### CODE REVIEW

**Review by jaacoppi — CHANGES_REQUESTED** [review]
Excellent work!

1. This is now three changes combined in one commit. Can you restructure this to be three commits?

2. Can you think of a test for dictionary_skipwords? Any words that clearly get broken if that fix is not included? Let's add the test as well.

After those two things this is ready for merging.

**Comment by hgneng** [comment]
What should I do to restructure one commit to three? Revert the commit do another PR?

Test for dictionary_skipwords needs patch 2 merged because words lines in cmn_listx seems to be ignored without patch 2.

**Comment by valdisvi** [comment]
No need to make new pull request. Make local changes and do forced push (`push -f ...` in command line) to your repository. Merge request will be updated automatically.

**Comment by jaacoppi** [comment]
> What should I do to restructure one commit to three? Revert the commit do another PR?

I would do it like this in your branch:
1. Backup
2. git reset HEAD~1	# remove the commit but keep the changes in the files
3. git commit src/libespeak-ng/tr_languages.c # for listx fix
4. git commit src/libespeak-ng/translate.c # for multi word fix
5. git commit <rest of the files> # for the third commit
6. write a test for dictionary_skipwords
7. git push -f to force push the PR.

Technically the test should come first and bugfix second. That way we know the test fails firsts and passes when the bug is fixed.
That can be done by reordering the commit lines with:
git rebase -i HEAD~5

**Comment by hgneng** [comment]
I do the following steps to update the commits. Please have another review. Thanks!
1. git reset HEAD~1
2. git commit -a -m 'Rewrite cmn_rules. Vowel will be spoken as Mandarin only when it's with a tone number. Otherwise, it will be regarded as English. This will make English words translated more correctly.'
3. make check passed
4. git commit -a -m 'add test for Mandarin word' // this test will pass after next two commits
5. make check not passed
6. git commit -a -m 'Fix issue of word item in cmn_listx not taking effect.'
7. make check still not passed
8. git commit -a -m 'Fix dictionary_skipwords bug. It should be injected when re-structing method TranslateWord3.'
9. make check passed now
10. git push -f

**Comment by jaacoppi** [comment]
@hgneng Thanks!

**Pull request merged**
