### PR TITLE
rule fix#1

### PR DESCRIPTION
**Pull request by king-dahmanus**
I've fixed a rule or 2. Note: I'm still unfamiliar with espeak's rule syntax and I only managed to get to this point with the help of the comments in the rules file

### CODE REVIEW

**Comment by king-dahmanus** [comment]
oh yeah, only murge this last one where the files are changed, as I don't know why I have those other 5 meaningless commits, so you may delete those and keep the one where I changed dictsource/ar_rules

**Comment by sthibaul** [comment]
Please also update the expected output in the test files, see the check failures

**Comment by king-dahmanus** [comment]
I don't know anything about the test files or how to make my changes
compatible. I told you before, I couldn't find a true sbs documentation to
tell me how this whole thing works, other syntaxes like the phoneme one
which I know, but there are things I can't understand: the rule syntax
being the most important of them

**Comment by jaacoppi** [comment]
@king-dahmanus see the documentation in docs/.

For tests, see the example in [add_language.md](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md).

For rules, see [dictionary.md](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md).

**Pull request closed without merging**
