### PR TITLE
Allow phoneme compilation without report generation

### PR DESCRIPTION
**Pull request by djphoenix**
When compile from read-only data bundle (shipped within iOS/macOS app), we can't write compile_report file.
The simplest solution is to (almost) silently discard it.

### CODE REVIEW

**Comment by jaacoppi** [comment]
I think we can just delete everything related to compile_report file.

Phoneme compilation is handled by the build system. If there's a failure the tests should find it. Producing a file for debug purposes seems useless. I don't think anyone understands the syntax of that file anyway.

**Comment by djphoenix** [comment]
I think about removal, but can't make decisions like this. If you (and other maintainers) sure, I can complete.

**Comment by jaacoppi** [comment]
Go ahead, remove the creation of phsource/compile_report.

**Comment by djphoenix** [comment]
> Go ahead, remove the creation of phsource/compile_report.

As your said)

**Comment by alex19EP** [comment]
can you Squash this 2 commits into one and then I will merge this.

**Pull request merged**
