### PR TITLE
Add stress marks to phoneme events

### PR DESCRIPTION
**Pull request by rotemdan**
I've added stress marks to phoneme events.

The implications of this are large for using `eSpeak-ng` as a phonemizer. It means that it's now possible to get accurate mappings between the phonemized  word and the original word (up till now it was pretty much impossible). This is huge for many applications that use it as a side-tool.

I have tested this for several weeks now, with many languages, and it seems to work correctly and produce results that should be identical to calling `espeak_TextToPhonemes` when the phonemes are in IPA mode (I haven't tested Kirshenbaum phoneme names though, but they should work as well - it's just that I'm using it via Emscripten and the IPA output flag is "burned" into the code).

This is the main method I've added to output the phoneme names with stress marks:

```c
char *WritePhMnemonicWithStress(char *phon_out, PHONEME_TAB *ph, PHONEME_LIST *plist, int use_ipa, int *flags) {
	if (plist->synthflags & SFLAG_SYLLABLE) {
		unsigned char stress = plist->stresslevel;

		if (stress > 1) {
			int c = 0;

			if (stress > STRESS_IS_PRIORITY) {
				stress = STRESS_IS_PRIORITY;
			}

			if (use_ipa) {
				c = 0x2cc; // ipa, secondary stress

				if (stress > STRESS_IS_SECONDARY) {
					c = 0x02c8; // ipa, primary stress
				}
			} else {
				const char stress_chars[] = "==,,''";

				c = stress_chars[stress];
			}

			if (c != 0) {
				phon_out += utf8_out(c, phon_out);
			}
		}
	}

	return WritePhMnemonic(phon_out, ph, plist, use_ipa, flags);
}
```
(The local constant `const char stress_chars[] = "==,,''";` is somewhat of a "hack". This should be a global constant, but I didn't want to modify other methods to use this)

That method is based, almost exactly, on a code fragment I found in `GetTranslatedPhonemeString`:
```c
		if (plist->synthflags & SFLAG_SYLLABLE) {
			if ((stress = plist->stresslevel) > 1) {
				c = 0;
				if (stress > STRESS_IS_PRIORITY) stress = STRESS_IS_PRIORITY;

				if (use_ipa) {
					c = 0x2cc; // ipa, secondary stress
					if (stress > STRESS_IS_SECONDARY)
						c = 0x02c8; // ipa, primary stress
				} else
					c = stress_chars[stress];

				if (c != 0)
					buf += utf8_out(c, buf);
			}
		}
```

However, the way it's done now - it's a **minor breaking change**. 

I guess it would be better to enable this feature via a flag, but I don't have sufficient knowledge of the codebase to implement something like that. 

I'll give this code to you people to decide how and if you want to integrate it.

I have more code to contribute: For example: I've enhanced the Emscripten port to support events (and phoneme events in particular), and I've tested it extensively for more than 6 months now.

### CODE REVIEW

**Comment by alex19EP** [comment]
@rotemdan are you still interested in this? can you try to fix the errors?

**Comment by rotemdan** [comment]
Yeah, sure. On `tests/api.c` there's a test that checks:

```c
if (enabled) {
		if (ipa) {
			TEST_ASSERT(strncmp(phoneme_events, "t ɛ s t  ", sizeof(phoneme_events)) == 0);
		} else {
			TEST_ASSERT(strncmp(phoneme_events, "t E s t _: _", sizeof(phoneme_events)) == 0);
		}
	}
```

I guess the the test strings need to be updated with the stress marks in order to pass.

I didn't see any errors other than this.

**Comment by alex19EP** [comment]
I think yes. can you update test? and alsoo add a changelog item?

> (The local constant const char stress_chars[] = "==,,''"; is somewhat of a "hack". This should be a global constant, but I didn't want to modify other methods to use this)

@sthibaul Do you think this won't cause problems?

**Comment by sthibaul** [comment]
>  (The local constant const char stress_chars[] = "==,,''"; is somewhat of a "hack". This should be a global constant, but I didn't want to modify other methods to use this)
> 
> @sthibaul Do you think this won't cause problems?

I don't see this as a real problem. It'd however be good to declare it as stress_chars[STRESS_IS_PRIORITY+1]  to make it obvious that it has the right size and we don't overflow it.

**Comment by rotemdan** [comment]
I updated the strings in the automated test. The tests now pass.

If I recall correctly, the line:
```c
const char stress_chars[] = "==,,''";
```

was basically copy and pasted from [this line in `dictionary.c`](https://github.com/espeak-ng/espeak-ng/blob/6cfd430bba1f47f08613cf76f5d34ec4220c6e3e/src/libespeak-ng/dictionary.c#L554), (and rest of the code was also copied, I believe). I left it as it is, I didn't want to change something that already worked. Also, especially since I wasn't really able to test the Kirshenbaum scheme directly. In my code I'm only using the IPA form (using eSpeak-ng via an Emscripten port, within the Echogarden speech toolset, so IPA phoneme event mode is hard-coded - and I don't need the other scheme).

Merging the updated upstream code created a number of "merge" commits. I don't know how to deal with them. Not really a Git expert.

I'm not sure how to exactly update the change log
* Which file? maybe `ChangeLog.md`?
* Which version? 1.52?
* Add new bullet point? At the top? bottom? etc.?

**Comment by alex19EP** [comment]
regarding merge commits. don't worry I deel with it.

as for changelog:

> Which file? maybe ChangeLog.md?

yep

> Which version? 1.52?

yes

> Add new bullet point? At the top? bottom? etc.?

yep add new  list item at the bottom. you can also append your nickname.

**Comment by rotemdan** [comment]
Given how it's usually styled, it seems that it's more appropriate to add a bullet point at the top, like:

### 1.52 (In Development)

*  Add stress marks to phoneme events (Rotem Dan)

android:
*  Added directBoot support -- beqabeqa473

updated languages:
*  ba (Bashkir) -- Andiv06
*  be (Belarusian) -- Andiv06, bespsm, Alaksiej Stankievič
*  cmn (Mandarin) -- Cameron Wong
...

---

Currently there are only the sections `android` and `updated languages`, so it makes more sense to put the change at the top, since it's not in asection. That's part of the reason I asked.

**Comment by alex19EP** [comment]
yep sorry that indeed is a better option. I haven't checked this file for a long time so forgot how it's structured.

**Comment by rotemdan** [comment]
Updated the changelog.

**Comment by alex19EP** [comment]
thank you for contribution.

**Pull request merged**
