### PR TITLE
Relicense speechPlayer code under GPL version 3.

### PR DESCRIPTION
**Pull request by datajake1999**
This pull request relicenses the speechPlayer code under GPL version 3, so it can legally be included in espeak-ng.

### CODE REVIEW

**Comment by datajake1999** [comment]
Permission was given from the author of speechPlayer in #844

**Comment by valdisvi** [comment]
I don't want to be nitpicking, but eSpeak NG is licensed with "GPL version 3 _or later_ license", which [may be problem](https://www.gnu.org/licenses/license-compatibility.html) if FSF will release newer version of the license.

**Comment by datajake1999** [comment]
Should I change the source files to state Version 3.0 or later?

**Comment by valdisvi** [comment]
Yes.

**Comment by datajake1999** [comment]
I changed the files to state GPL version 3 or later, and squashed all licensing changes into a single commit.

**Comment by valdisvi** [comment]
Thanks!

**Pull request merged**
