### PR TITLE
new voice variants

### PR DESCRIPTION
**Pull request by joshknnd1982**
Here is a zip file with new voice variants for espeak master and for android. Please include all of these variants because they make espeak sound much better... closer to decTalk or eloquence so plelase include all of these new variants, removing older variants if needed from original variants list. thanks. 
[espeaknewvariants.zip](https://github.com/espeak-ng/espeak-ng/files/10948933/espeaknewvariants.zip)

### CODE REVIEW

**Comment by hozosch** [comment]
In my view, there's no way ESpeak will sound like eloquence or dectalk, because those synths also produce their consonant sounds with klatt phonemes. However, with eSpeak, the recorded consonants remain, which has a significant impact on the sound. Also, the way ESpeak deals with klatt phonemes also makes it sound more robotic than dectalk.

**Comment by joshknnd1982** [comment]
I agree it doesn't and won't sound like decTalk or eloquence. But even so, the new variants make it sound a lot better.

**Comment by 0x5066** [comment]
That is not how a pull request works, you're supposed to fork the repository, upload all the files to their respective directory (which is /espeak-ng-data/voices/!v), then make the proper pull request. Attaching a zip file here is pointless because **you** are supposed to add these to the repository, not them.

**Comment by alex19EP** [comment]
what @0x5066 said.

**Pull request closed without merging**
