### PR TITLE
Fixed Haitian Creole rules to better match Wikipedia article

### PR DESCRIPTION
**Pull request by calcwatch**
I'm not a Haitian Creole speaker, but I'm going by the rules listed in https://en.wikipedia.org/wiki/Haitian_Creole#Orthography. The results sound closer to what I'd expect.

I'm not sure why there were nasalized vowels like ã in the rules, so I've removed them.

I also couldn't find existing phoneme definitions for a couple sounds, so I left TODO notes for the future.

### CODE REVIEW

**Comment by valdisvi** [comment]
Rules containing `...(K` are wrong. What you wanted to mean by them?

**Comment by calcwatch** [comment]
> Rules containing `...(K` [are wrong](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md). What did you want to mean by them?

I mean "apply this rule if the sequence is not followed by a consonant".

So for `an(K      A~`:
j**an**bon => /ʒ**ɑ̃**bˈɔ̃/

But:
**an**ana => /**an**ana'/

Should it be `an (K      A~`?

**Comment by valdisvi** [comment]
Then it is `...(C`

**Comment by calcwatch** [comment]
The problem with `...(C` is that it doesn't cover the case when a word ends with `an`.

For example, this is correct:
**an**ded**an** => /**ɑ̃**dedˈ**ɑ̃**/

An `an(C` rule would produce /ɑ̃dedˈ**an**/.

**Pull request closed without merging**
