### PR TITLE
Some improvements to German

### PR DESCRIPTION
**Pull request by hozosch**
This is another trie in improving the German espeak. There are just very few changes to phonemes, and some fixes for words in the rules and list files.

### CODE REVIEW

**Comment by valdisvi** [comment]
Because of conflicting changes of  dictsource/de_list dictsource/de_rules phsource/ph_german files, we can't know, what to do with changes.
Please review highligted differences in [uploaded video](https://files.fm/u/hd8utcnw) (at left — previous version of the file, in the middle merged or "to be" version, and at the right your version).

**Comment by rhdunn** [comment]
I'm looking at merging it at the moment. Don't worry about any merge conflicts, as I tend to merge locally instead of using the GitHub merge UI.

**Comment by valdisvi** [comment]
Good!
I also tend to merges locally. But this case looks insane even in [meld](http://meldmerge.org/)...
Hozosch maybe you will help new possibility to change, and build eSpeak NG [on-line](https://odo.lv/EspeakGuide).

**Comment by rhdunn** [comment]
Yeah. I have had a look through the changes and have some comments.

1.  The changes are based on an older commit of espeak-ng. This makes it harder to merge if/when additional changes have been made.

1.  Can you make sure that the phoneme files build before committing the changes? The `EI` phoneme change duplicates the `phoneme EI` line, which breaks the current build.

1.  The main conflict comes from these changes being based on the previous German changes which I reverted due to feedback (https://groups.io/g/espeak-ng/message/1279).

Can you recreate the fixes from the latest commit instead of an older version?

It might be better to describe the changes and fixes you are trying to make. Some of the changes (e.g. the "a" at the end of `beta` and `komma`) don't match standard German, which espeak/espeak-ng follow with the `a` phoneme instead of the `A:` phoneme you are using.

There are clearly some errors we can fix (e.g. the feature definition for the `b` phoneme, but things like the changes to the phonemes to use the base definitions may be something worth discussing with other German espeak users. I'm also curious if some of the changes are accent specific.

**Comment by hozosch** [comment]
If I were to update the version, I would commit to this pull request which I don't intend to do. The problem is, I always actually do it from espeak 1.48.15 which still has got some long names for phoneme types! So I have to convert to the espeak ng way. I unfortunately can't try the online building, because I don't have an account on odo.lv yet, and I cannot complete the form since I'm not able to see the captcha due to my blindness, and I don't believe web visum is available for chrome. I could ask for sighted help, but I don't feel like doing that.

**Comment by valdisvi** [comment]
Hozosch, please send me private e-mail to valdis@odo.lv and I'll create account for you.

**Pull request closed without merging**
