### PR TITLE
Add L02 for vowels, keep tones always behind vowels

### PR DESCRIPTION
**Pull request by ronaldaug**
## shn_list
- Add consonants in shn_list
- Fix `p_h` to `f`
- Remove 1 from shn_list as it's default tone

## shn_rules
- Add vowels group as `.L02`
- Keep tones always behind vowel

### CODE REVIEW

**Comment by sthibaul** [comment]
please see the make failures:

```
 3961: Bad phoneme [.] (U+2e) in: ဢိုၵ်း  ai.k4
```
etc.

**Comment by ronaldaug** [comment]
> please see the make failures:
> 
> ```
>  3961: Bad phoneme [.] (U+2e) in: ဢိုၵ်း  ai.k4
> ```
> 
> etc.

Thanks @sthibaul. It's strange, I'm not quite sure it's because of a character `a` (I recently added) or `.` . Actually, `.` is already in master [here](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/shn_list#L3943-L3944) without a problem

**Comment by sthibaul** [comment]
It seems removing the a did help. Now you need to update `tests/language-phonemes.test` with the new produced checksum, to reflect the actual change

**Comment by ronaldaug** [comment]
> It seems removing the a did help. Now you need to update `tests/language-phonemes.test` with the new produced checksum, to reflect the actual change

I had the kind of unit test issue before and [**Valdisvi** pointed me here](https://github.com/espeak-ng/espeak-ng/pull/543#issuecomment-415981917). I had to changed the ID hash number and it passed the test.

However, before I go any further, I just want to make sure I understand it. Could you share me a reference to read about  `tests/language-phonemes.test` ? 
Also can I just add a random hash ID for `shn` to make it pass the test? 

Thanks in advance.

**Comment by sthibaul** [comment]
Urgl, this wasn't meant at all to be so

**Comment by sthibaul** [comment]
I didn't plan to merge this branch, since I have really little knowledge about language files etc.

I have no idea why the bot suddenly force-pushed your previous commit.

The fact that github thinks the MR is now merged is just because it happened to only contain the latest commit 21ea0ac.

I guess you can try to just push again your commits on your `[ronaldaug:master](https://github.com/ronaldaug/espeak-ng)` branch

**Pull request merged**
