### PR TITLE
Fixing sequences of ? and !

### LINKED ISSUE #583: Sequence of punctuation signs handling
Hi,

Generally, espeak is not fond of multiple punctuation signs like !!! or ?!! . It will tend to parse them as multiple clauses (which is logical) and as such, because the last signs of the sequence are isolated in their own clause, they will be spelled by espeak. E.g. 'Hi !!!' will result in 'Hai exclamation'. This should probably be taken into account since it's quite frequent in modern written speech. It also seems related to #369 to me, isn't it?

Best.

### PR DESCRIPTION
**Pull request by BenTalagan**
Hi, this is an attempt to fix #583. This specifically targets sequences of `?` and `!` (like `?!?!!!`,`???`, `!!!`, etc) and treats the whole sequence as its first char only.

### CODE REVIEW

**Comment by valdisvi** [comment]
@rhdunn may review and merge this pull request.
But I think, that instead of patching this very complicated logic in pure C, we should refactor espeak-ng that it uses some external/rewritten text tokenization with configuration files (like patterns for dates, phone numbers, abbreviations etc.).
The biggest issue I see for Latvian, Arabic and other languages is, that all tokenization rules in espeak-ng are based only around current cursor/character, but tokenization would be much easier to handle, if it would work on the whole sentence (clause in espeak-ng) with rules written in configuration files with something like regular expressions.
See e.g. issues #369, #368, #199, #366.

**Comment by BenTalagan** [comment]
I do agree with you, all the more that the tokenization source code is really hard to read currently, and it often mixes languages. A clean and customizable tokenization algorithm would be great as it would also allow to provide a structured output from espeak-ng. This PR is really an emergency hack to fix an annoying corner case.

**Comment by rhdunn** [comment]
I think it makes sense to patch the current logic to address current bugs. My main comment for this fix would be that it would be better to check the `ucd_properties` value (to handle other Unicode question and exclamation marks). That is read/used by `punct_data` below this check, so it would be better to make use of that (e.g. `punct_data & (CLAUSE_QUESTION | CLAUSE_EXCLAMATION)`) on the if statement, then in the while loop use `clause_type_from_codepoint(c2)` instead of `punct_data` when checking the clause flags.

The more general changes will still need C code to process the logic (like with number processing, tokenizing SSML/HTML, etc.). It makes sense to have the configuration (like the current tr_languages.c code) to be in language configuration files. And the espeak code definitely needs improving w.r.t. Unicode processing. What I'm not sure about is what the balance between configuration and general processing logic will be.

**Comment by BenTalagan** [comment]
Ok here's a second attempt based on your remarks. Tests are passing. If the PR is ok for you, don't forget to squash-merge all commits into one to get rid of the first attempts :-)

**Comment by rhdunn** [comment]
Looks good. I've used cherry pick to combine and merge the commits as requested. Thanks.

**Pull request closed without merging**
