### PR TITLE
add SpeechPlayer as Klatt6

### PR DESCRIPTION
**Pull request by datajake1999**
I managed to add NV SpeechPlayer as Klatt 6. I also was able to remove the Windows specific code from speechPlayer, and the library still works. I am using it with NVDA as I write this.
I updated the visual studio project with the new source files. To update the other projects, you should add the following files:
* libespeak-ng/sPlayer.c
* speechPlayer/frame.cpp
* speechPlayer/speechPlayer.cpp
* speechPlayer/speechWaveGenerator.cpp
I also added a compiler define for including SpeechPlayer, INCLUDE_SPEECHPLAYER.

### CODE REVIEW

**Comment by hozosch** [comment]
Wow! I seriously didn't expect that. That is just great! NVAccess should update ESpeak NG as soon as possible.

**Comment by datajake1999** [comment]
I hope NV Access updates espeak-ng soon as well.
Once we get speechPlayer compiling with g++, we would also be able to get this running on Linux. To clarify the Windows function calls were removed from speechPlayer, but their are some G++ compiler errors that need to get fixed before we enable speechPlayer support on Linux.

**Comment by rhdunn** [comment]
This looks good as an initial pass to get the code integrated.

When the Linux support is done later on, it would be helpful to make this use C instead of C++ (as that is what the rest of the project is using) and make it more in line with the code style of the project.

**Comment by datajake1999** [comment]
Agreed. It shouldn't be too hard to port speechPlayer to C. For now, I think we should merge this since it clearly works.

**Comment by datajake1999** [comment]
speechPlayer now compiles with g++.

**Comment by datajake1999** [comment]
I added speechPlayer support to the Linux build system. I haven't had the chance to test it much, so please let me know if their is anything I need to change. Before testing you need to build and install the speechPlayer library. I have included a makefile to do this.

**Comment by datajake1999** [comment]
I just tested building espeak-NG with speechPlayer on Ubuntu MATE, and it actually works!

**Comment by datajake1999** [comment]
I am attaching a windows build of this for anyone who wants to test this with NVDA.
[espeak-ng-klatt.zip](https://github.com/espeak-ng/espeak-ng/files/5610401/espeak-ng-klatt.zip)

**Comment by hozosch** [comment]
This version of speech player doesn't have access for all parameters, like the one in your addon has. Is there a reason for this?

**Comment by datajake1999** [comment]
I decided to have a fresh start with NV Accesses code, since they already had espeak-NG support. My version was based on eSpeak 1.48.15. If their is enough interest, I can bring some of these parameters back.

**Comment by hozosch** [comment]
Well I'd like to have those back, because my variant tom had a nice smoothness which isn't there if those parameters are missing. Also, I like the default klatt voices better how they were in your addon. But of course, that's just me.

**Comment by datajake1999** [comment]
For now I want to merge NV Accesses original work, and I will probably add more speechPlayer parameters for voice files as a future pull request.

**Comment by datajake1999** [comment]
I updated the build instructions with information about speechPlayer. I also created a pull request on the official NVSpeechPlayer repo with my cross-platform changes to the library. If these changes get merged, I can remove the speechPlayer code from my branch and provide a link to the official NVSpeechPlayer repo in building.md.

**Comment by rhdunn** [comment]
The CI build is failing due to a byte order mark present in the building.md file. Can you remove that please.

Can you also have the main automake file build the speechplayer code when the speechplayer is enabled? That way the build logic is all in the same place. The autoconf checks for the C++ compiler should be guarded around when speechPlayer is enabled, so the espeak-ng library and executable can still be built with a C compiler.

Other than that, it looks good. It would be worth getting a version with speechPlayer building on travis/CI in addition to the current one without, so we have build/test coverage for when it is enabled.

**Comment by datajake1999** [comment]
I fixed the BOM.
I am not sure how I should integrate the speechPlayer build process into the espeak-ng Autoconf system. Is it still a good idea to build and install speechPlayer as a shared library on the system then link it with libespeak-ng? If so, how  exactly can I automate this with the current build system? I am still fairly new to Autoconf.

**Comment by datajake1999** [comment]
I decided to ad the speechPlayer build process into the espeak-ng autoconf system. For some reason I am getting a linker error that says error adding symbols: DSO missing from command line.

**Comment by hozosch** [comment]
Cool how you end up figuring out things on your own. I tend to do the same, but it doesn't always work.

**Comment by datajake1999** [comment]
Integrating the speechPlayer build process into autotools is starting to drive me crazy. The last few commits are different things I have tried. Nothing works.
A c port of speechPlayer would be nice, but since the library uses some C++ functions, porting won't be as easy as I thought. I still want to get this merged though, because a lot of people like the speechPlayer Klatt implementation.

**Comment by hozosch** [comment]
Oh, I see. I hope that you will get feedback from more experienced people soon :D

**Comment by datajake1999** [comment]
I got speak-ng to link correctly by compiling a dummy speak-ng.cpp file if building with speechPlayer.

**Comment by datajake1999** [comment]
We now have espeak-ng with speechPlayer building on Travis CI!

**Comment by josephsl** [comment]
CC @MichaelDCurran

**Comment by valdisvi** [comment]
@datajake1999, can you clean up commit history of this pull request that it doesn't have forward and backward changes of unsuccessful attempts? Then I could merge it without any doubts.

**Comment by datajake1999** [comment]
Done! I squashed the last 35 commits into a single commit.

**Comment by valdisvi** [comment]
@michaelDCurran

**Comment by michaelDCurran** [comment]
Firstly, this is cool that speechPlayer has been incorporated into eSpeak. Well done @datajake1999  for all the work. 👍
 However:
I have not worked on speechPlayer for quite some time, and cannot promise that I will have the time to fix any bugs or make any additions. The eSpeak-ng project takes this code as is, though I am happy to answer occasional questions on its history or implementation details if needed.
I must also point out that there is most likely a licensing issue here. eSpeak-ng is GPL3 or later, where as speechPlayer is specifically GPL 2.0. Perhaps it should have been LGPL, or GPL 3, but at the time I decided upon GPL 2. It is my understanding you cannot mix GPL 2 code with GPL 3 code.
However, as NV Access and I were the only contributers to the speechPlayer project, I thereby give permission from myself and on behalf of NV Access Limited, to have this copy of speechPlayer re-licensed to GPL 3 if legally necessary for eSpeak-ng to continue incorporating it.

**Comment by datajake1999** [comment]
A relicense of this copy of speechPlayer code is fine by me.

**Comment by datajake1999** [comment]
I just opened a pull request regarding the licensing issue.

**Comment by datajake1999** [comment]
@michaelDCurran, the licensing issue has been resolved.

**Pull request merged**
