### PR TITLE
Changes for Shan language

### PR DESCRIPTION
**Pull request by ronaldaug**
- Reorder consonants
- Fix 6 tones
- Remove prefixes **_)**
- Add comments in **ph_shan** for a better understanding.

### CODE REVIEW

**Comment by ronaldaug** [comment]
Hi @valdisvi 

Can I have a rule like if there is a single prefix, it will add a letter **a**?

The problem is when a single consonant ( e.g `လ` ) is combined with the suffixes such as `မ်` it should be like `lam`. But currently it produces`lm`.

I could change the rule for `မ်` like `am`. But this is not correct for every rules. 
e.g `လိမ်` is equal to `lim` , if I change `မ်` to `am`, it would be `liam` and this will produce an  incorrect sound.

Thanks in advance

**Comment by rhdunn** [comment]
See the prerule group example in https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#rule-groups. For example:

    .L01 လ // Consonants

    .group မ်
        .L01) မ် am
              မ် m

**Comment by valdisvi** [comment]
In general, you should use some approaches of following:
```
...
.group လ
    လ        l   // default pronunciation (shortest string means lowest weight)
    လ   (မ်   lam // only la is consumed, analysis will go to ma as nex character
    လမ်       lam // all letters are consumed, rule analysis will go to character after asat
    လ   (ိမ်   lim // only la is consumed, analysis will go to i character
    လိမ်       lim // all characters are consumed, analysis will go character after asat
...
```
See details about [pre and post groups](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#special-characters-in-both-pre-and-post).

Also, you could set your own [letter groups for rules](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#rule-groups) `L01`, `L02` etc, and also you can redefine consonants (meaning of `C` in rules) and vowels (`A` in rules) in [tr_languages.c](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c) file. For example, as it is set for letters [A,B,C,F,G,H,Y in Arabic](https://github.com/espeak-ng/espeak-ng/blob/20096dc1bf97a87aa59924cbae3a59a6e2894306/src/libespeak-ng/tr_languages.c#L376)

**Comment by ronaldaug** [comment]
Thank you so much for helping me. 

One more question.
```
         ၵၢႆ       ka:i  
         ၵွႆ       kOi
         ၵုၺ်     kui   
         ၵူၺ်     koi 
```
Here If I change the last `i` to `j` , it sounds more accurate. 
But I don't see any `j` letter in ph_shan and `vowel` directory. 
Actually I want to try something like`FMT(vowel/j)`, would it be ok?

**Comment by valdisvi** [comment]
`j` sound comes from [phonemes](https://github.com/espeak-ng/espeak-ng/blob/1fa6d52a918f3e574240a32ba75092c350e9c5ef/phsource/phonemes#L643) file, which is then [extended/overriden](https://github.com/espeak-ng/espeak-ng/blob/1fa6d52a918f3e574240a32ba75092c350e9c5ef/phsource/phonemes#L1788) by [ph_shan](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_shan) file. Look for more in [phontab.md](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md) file.

**Comment by ronaldaug** [comment]
Thanks @valdisvi 

I'm sorry that [Travis check](https://travis-ci.org/espeak-ng/espeak-ng/jobs/585988204
) failed again, It's kinda intimidating for me. 

If I am not wrong there is no conflict with my forked repo and espeak master.

Could you please check [shn_rules](https://github.com/ronaldaug/espeak-ng/blob/master/dictsource/shn_rules) for me? Thanks.

Actually, I only changed a single file  **shn_rules** .

**Comment by valdisvi** [comment]
You have used undefined phoneme `ɨ` in [shn_rules](https://github.com/ronaldaug/espeak-ng/blob/7bfa1eac26696f177986f0b1bcc1ee8b5c03238c/dictsource/shn_rules#L169) file.
Either use some other already defined phoneme (you can find definitions with command `egrep -r "^phoneme\s+\w+" phsource`) or [define](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md#phoneme-definitions)  `phoneme ɨ` in ph_shan file. I don't recommend using non-Latin character for phoneme name though, because that would not follow [Usenent/X-SAMPA](https://en.wikipedia.org/wiki/Comparison_of_ASCII_encodings_of_the_International_Phonetic_Alphabet#Symbols) phoneme naming convention used in espeak-ng. If you like, you can add `ipa  ɨ` entry in phoneme definition instead.

**Comment by ronaldaug** [comment]
Uh, it was my bad. I should've copied phoneme `W`. It passed Travis check now. Thanks.

**Pull request merged**
