### PR TITLE
Updates italian source dictionaries

### PR DESCRIPTION
**Pull request by Christianlm**
Add some rules and exceptions for italian language.

### CODE REVIEW

**Comment by jaacoppi** [comment]
Something wrong with CI. Checks pass but the result is not reported. @sthibaul @djphoenix any ideas?

This can be merged.

**Comment by djphoenix** [comment]
I am not sure at all, seems like CI stuck on any PR.

**Comment by sthibaul** [comment]
It was an issue in the project configuration that wasn't updated after the CI rules names were complemented with OS name. Now fixed.

**Comment by sthibaul** [comment]
and now it's other PRs which are stuck on missing the new rules names... I'm trying to rebase them so they get to re-run everything.

**Pull request merged**
