### PR TITLE
Enhance detection of gradle

### PR DESCRIPTION
**Pull request by ryandesign**
I propose these further enhancements to the detection of gradle.

Commit messages reproduced for easier reading:

---

**Check more accurately if gradle exists**

Previously, the configure script would only successfully determine that gradle exists if the user specified an absolute path to the executable. It would fail if the user specified only an executable name or if the default value of "gradle" were used. Now it should succeed in either situation.

---

**Remove unnecessary curly braces around var name**

---

**Show in configure summary when gradle is not found**

Previously, if configure determined that gradle could not be found, the summary at the end of the configure output would nevertheless print the name or path of the nonexistent gradle executable that it tried to find. Now it clears that variable.

---

**Set HAVE_GRADLE in a more autoconfy way**

It is perhaps more autoconfy to have AM_CONDITIONAL evaluate a variable rather than call it with what are essentially constants representing either true or false. It might be even more autoconfy to use AC_CHECK_PROG here instead; I don't know if there's a good reason why that wasn't already done here.

### CODE REVIEW

**Comment by ryandesign** [comment]
As a further enhancement, the Makefile targets that depend on gradle (apk-release, apk-debug, apk-check) could be changed so that if gradle is not found they print a reasonable error message.

**Comment by valdisvi** [comment]
I'm not sure proposed changes improve much:

```
if command -v "$GRADLE" >/dev/null; then
```
uses Bash builtin `command`, but (at least in theory) eSpeak NG supports any shell.

`AC_MSG_RESULT([$GRADLE])` instead of `AC_MSG_RESULT([${GRADLE}])`
is just shorter, but longer one is also correct, even though more ceremonial.

You need to initialize 
`GRADLE=`
to later use 
`AM_CONDITIONAL(HAVE_GRADLE, [test x"$GRADLE" != x])` instead of
`AM_CONDITIONAL(HAVE_GRADLE, [test 1 = 0])` which is actually more complicated.

So in total, proposed changes seem just different flavour of implementation, but not much better than it is now.

**Comment by ryandesign** [comment]
> I'm not sure proposed changes improve much:

I explained in the commit messages what the impovements are.

> `if command -v "$GRADLE" >/dev/null; then` instead of `if test -e ${GRADLE} ; then` uses Bash builtin `command`, but (at least in theory) eSpeak NG supports any shell.

I wasn't aware that `command` is bash-specific and I don't think I have a non-bash POSIX-only shell to test with. If this is true, then an alternative could be used.

The current code (`test -e ${GRADLE}`) is broken in the way I described in the first commit message. The discovery of this problem is what led me to begin the modifications that I've submitted here.

> `AC_MSG_RESULT([$GRADLE])` instead of `AC_MSG_RESULT([${GRADLE}])`
> is just shorter, but longer one is also correct, even though more ceremonial.

As I said in the second commit message, I was merely removing unnecessary and uncustomary curly braces, which matches how other variables are referred to in the script.

> You need to initialize
> `GRADLE=`
> to later use
> `AM_CONDITIONAL(HAVE_GRADLE, [test x"$GRADLE" != x])` instead of
> `AM_CONDITIONAL(HAVE_GRADLE, [test 1 = 0])` which is actually more complicated.

Using `test 1 = 0` in `AM_CONDITIONAL` is a nonsense thing to write since one always knows what the result will be. I was just trying to make the code make more sense and do things in what I believed was more in line with the way that the developers of autoconf intended. I am not an autoconf expert, I have not written autoconf scripts, but I have read and patched many.

**Comment by lucaswerkmeister** [comment]
> > `if command -v "$GRADLE" >/dev/null; then` instead of `if test -e ${GRADLE} ; then` uses Bash builtin `command`, but (at least in theory) eSpeak NG supports any shell.
> 
> I wasn't aware that `command` is bash-specific and I don't think I have a non-bash POSIX-only shell to test with. If this is true, then an alternative could be used.

`command` [is in POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html), for what it’s worth, including the `-v` option. The [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=sh&sektion=1&manpath=FreeBSD+14.0-current), [OpenBSD](https://man.openbsd.org/sh#command) and [NetBSD](https://man.netbsd.org/sh.1) `sh` versions all have it as a built-in command. For Apple systems, [Bash 3.x](https://github.com/bminor/bash/blob/bash-3.2-beta/doc/bash.1#L6182) and [zsh](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html) also have a `command -v` builtin.

**Pull request merged**
