### PR TITLE
crh: Add initial support for Crimean Tatar language

### PR DESCRIPTION
**Pull request by Andyvladescu73**
I added initial support for Crimean Tatar language. Did the rules for most common phonetic rules that are in place for Crimean Tatar, and the ability to more easily make improvements to the phonemes, rules, and exceptions. Current status is early testing, but voice is mostly understandable at this point, and pronounces numbers by the correct rules now.

### CODE REVIEW

**Comment by sthibaul** [comment]
here again the hash is not coherent

**Comment by Andyvladescu73** [comment]
Oh, sorry! Well, I would mind if you could give me a hash for "crh" please?

**Comment by sthibaul** [comment]
Again, see the failure log, `a7d1eca9113db939f899ff4134a2319f8a143c48 != b3ed1a1fd52dd2de32acf68c5cf908c81ebdbeea`

There's also an issue in `language-pronunciation`: ` c'e ? ,@*@mtAt'Ar t;Il'I != q@*@mtAtArdZ'A`

**Comment by sthibaul** [comment]
Again, There's also an issue in language-pronunciation:

```
c'e ? ,@*@mt,AtArdZ'A
c'e ? ,@*@mtAt'Ar t;Il'I != q@*@mtAtArdZ'A
q@r@mtAt'Ar t;Il'I
```

**Comment by sthibaul** [comment]
Why did you remove the quotes? That won't fly at all. The log is telling you that there is `c'e ? ,` instead of `q`

**Comment by Andyvladescu73** [comment]
That's it, I'm done editing! But what is the name of a device for hashing so that there are no failures on the foreign language using writing like test_phon and how to write that corresponding language after putting those letters, for example. should I put it on the language-phonemes.test file? I also want to know that I don't understand what you brought to my mind that I want to deal with in the future after I created that language on espeak-ng, putting on github everything I pushed to that branch...

**Comment by Andyvladescu73** [comment]
well, it can't be that I worked on that edit, I can't repeat it 100 times. In one way or another, it was enough for that language made by me to work well!!

**Comment by Andyvladescu73** [comment]
If, I just add c,e?, in this pronunciation it will not sound good in the future if I make a mistake in a pronunciation. This is how it is pronounced, and it should sound like this: "Qırımtatarca, Qırımtatar tili". You don't have to worry about them, because I barely worked on them the whole time...

**Comment by sthibaul** [comment]
> If, I just add c,e?, in this pronunciation it will not sound good in the future

I'm not saying that you want to add it, I'm saying that this is what the test currently obtains. Either fix the test, or fix the rules to produce what you expect.

**Comment by Andyvladescu73** [comment]
I solved the problem!

**Comment by Andyvladescu73** [comment]
Dar, nu-i nimic. Ca probabil am uitat din greseala sa pun ghilimelele la fisierul care scrie crh la language-pronunciation.test

**Comment by sthibaul** [comment]
again, see the failing checks logs:

```
c'e ? ,@*@mt,AtArdZ'A
c'e ? ,@*@mtAt'Ar t;Il'I != q,@*@mt,AtArdZ'A
q,@*@mtAt'Ar t;Il'I
```

they are saying that your current rules produce `c'e ? ` instead of `q`

**Comment by Andyvladescu73** [comment]
So what? If I put a c,e here in the respective file, you can hear that q or "what? I don't understand anything...

**Comment by sthibaul** [comment]
This file is a *test*. It's not saying that happens, it's writing down what you expect your rules should be doing. If tests are failing, either it's the test which is wrong, or it's the rules that are wrong, and should be fixed to match what the test expects.

As for `c'e ?` vs `q` I have no idea what is right, since I don't speak the language. You need to check what is right, and either fix the test, or fix the rules.

**Comment by Andyvladescu73** [comment]
I tried several times in this sense, but I did not succeed. Please excuse me for any considerable errors, I couldn't do it anymore, I tried. Better to leave it like that than to fix it like this...

**Pull request closed without merging**
