### PR TITLE
Cherokee language improvements.

### PR DESCRIPTION
**Pull request by michael-conrad**
Misc Cherokee language improvements.

### CODE REVIEW

**Comment by valdisvi** [comment]
Thanks, @michael-conrad I merged it into project.
Note, that I merged your pull request as single commit, because not all your commit messages highlighted actual changes, and because of entangled interim merges between your commits and master tree of the project made unnecessary branches, which could make search for regressions with bisecting much harder.

**Comment by michael-conrad** [comment]
What is a good way to prevent that pull push merge weirdness? When I merged
back into my branch it was all crazy with push pull merge steps.

**Comment by valdisvi** [comment]
If you have enough patience and don't depend on other changes coming from the project, you don't do merges yourself. You just wait for merge to happen on the upstream project on github and then just pull updates (and merges) from there to your local project.
Or, you can always simplify development history on your own local project yourself, what requires advanced usage of the git.

**Comment by michael-conrad** [comment]
This seems to work to get my master back in sync:

git fetch upstream
git reset --hard upstream/master
git push -f origin master

**Pull request closed without merging**
