### PR TITLE
Catalan: Major fixes

### PR DESCRIPTION
**Pull request by c-armentano**
We have implemented formal catalan rules, specifically the list below (in catalan)

- [x]  Paraules amb 2 accents fònics (primari i secundari): benvingut, contrasenya...
- [x]  Emmudiment: m davant b o p (camp, rumb,...), t o d finals precedides de n o l: (tant, molt, fent...)
- [x]  Sensibilització: t a final de mot amb contacte vocàlic: fent-ho, parlant-ho, sant Andreu vs. sant Joan
- [x]  Sonorització: essa a final de mot: les ales vs. les sales
- [x]  Paraules amb [hac_aspirada](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_hac_aspirada): halar
- [x]  Paraules amb [ics intervocàlica darrere de i](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_ics_intervoc%C3%A0lica): afixar, fixar vs. pixar
- [x]  Paraules amb [ics travada darrere de i](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_ics_travada_darrere_i_voc%C3%A0lica): crucifix, afix vs. guix
- [x]  [Pronúncia en català amb erra interior muda](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_erra_interior_muda)
- [x]  [Pronúncia en català amb erra final sensible](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_erra_final_sensible)
- [x]  [Pronúncia en català amb erra vibrant intervocàlica](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_erra_vibrant_intervoc%C3%A0lica)
- [x]  [Pronúncia en català amb gu formant hiat](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_gu_formant_hiat)
- [x]  [Pronúncia en català amb i inicial no consonàntica](https://ca.wiktionary.org/wiki/Categoria:Pron%C3%BAncia_en_catal%C3%A0_amb_i_inicial_no_conson%C3%A0ntica)

### CODE REVIEW

**Comment by gullabi** [comment]
Hi. Can we get feedback on our PR? We are currently adding dialect support for Catalan. It would be good to know maintainers' feedback, before we advance much more.

We are also interesting in having this merged as soon as possible since we are using espeak as g2p tool for training our neural TTS voices. Thanks.

**Comment by jaacoppi** [comment]
Sorry, this PR has gone unnoticed for too long.

Tests fail. You should rebase to current main and fix the tests.

**Comment by gullabi** [comment]
Thanks for the message, now we were delayed in response. The reason is that in the meantime we improved espeak in catalan considerably more. Apart from doing the rebase, we are now introducing our improvements to branch of the PR.

**Comment by c-armentano** [comment]
We've already updated the repository and will wait for your approval

**Comment by jaacoppi** [comment]
Tests still fail. Check the reason and ask for help in fixing them if needed.

**Comment by gullabi** [comment]
The errors (at least the majority of them) seems to be caused by

```
CMake Error: Unknown argument: -Ttest
CMake Error: Run 'ctest --help' for all supported options.
```

It seems to be related to how the tests are launched and not to something we have introduced. We appreciate if you could look into it also.

**Comment by c-armentano** [comment]
Hi,
we found out that we are missing the phoneme tests in tests/language-phonemes.test for the variants we added. Would you mind providing us the corresponding documentation?

Kind regards,

**Comment by c-armentano** [comment]
Good morning,
We did a new commit. Do you know when the tests could run again? 
Thank you

**Comment by c-armentano** [comment]
Hello,
We couldn't pass the tests because of a cmake failure. Could you give us a hand with resolving it?
We have seen that the [documentation](https://github.com/espeak-ng/espeak-ng/blob/d5107e8c2d80eb07c14f5687dd32d452d2ca59d9/docs/building.md) on how to install espeak with cmake is still a draft, so we would need some help with this.
Thank you

**Comment by c-armentano** [comment]
Hi @jaacoppi,
 
It seems like there it was a problem regarding a change in the ctest code, you can find the information about this change [here](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9383).

Hence, we have changed the `-Ttest` from three different .yml files into `-T test`, and now the cMake execution doesn't fail.
Therefore, this PR includes both these changes and the Catalan modifications.

Everything seems to be working, please, let us know if all is fine.

Thank you

> The errors (at least the majority of them) seems to be caused by
> 
> ```
> CMake Error: Unknown argument: -Ttest
> CMake Error: Run 'ctest --help' for all supported options.
> ```
> 
> It seems to be related to how the tests are launched and not to something we have introduced. We appreciate if you could look into it also.

**Comment by hammera** [comment]
With @sthibaul doed CI fix perhaps resolving the workflow checks related problem in Catalan language files related too.
The merged pull request number is following:
#1971 
A free maintainer have possibility to approwe waiting 9 checks this Catalan PR related?
Me not have approve right unfortunate to enable the waiting workflows running.

Kind regards,

Attila

**Comment by sthibaul** [comment]
> The merged pull request number is following: #1971 A free maintainer have possibility to approwe waiting 9 checks this Catalan PR related?


It's  already merged.

**Comment by mllopartbsc** [comment]
@sthibaul It seems like all tests have passed, could you merge our changes when possible please?

Kind Regards

**Pull request merged**
