### PR TITLE
Fix some pronunciations in spanish.

### PR DESCRIPTION
**Pull request by rmcpantoja**
# New foreign words
* Down
* ETI
* File's
* freedom
* gmail
* Hitler
* Instagram
* Junior
* Kepler
* scientific
* Telegram
* unigram
* Up
* YouTube

# Abbreviations

* aprox (Aproximadamente)
* A. C. (antes de cristo)
* D. C. (después de cristo)
* ej. (Ejemplo)
* etc (etcétera)
* pag. (página)
* SAR (su alteza real)
* SNM (sobre el nivel del mar)
* SSS (servicio social sustitutorio)
* tel. (teléfono)
* tqm (te quiero mucho)

# misc words:
* Progrom

### CODE REVIEW

**Comment by gregodejesus** [comment]
hi, it will be possible for an upcoming correction to add the words files=fails, down=dawn, up=ap, ETC=etcétera, YouTube=yutub and to differentiate the pronunciation (at least in spanish latin american) the words that start or have a letter b and v as the word inventar that sounds the same as the letter b, also try to at least differentiate in verbalization the letter s and apply the same pronunciation in the letter c, z, since the two are pronounced like the s in character navigation in the pronunciation 
in Latin Spanish?
do the same as was done with the word JAWS, hardware, free ETC.
In terms of words in the letter r, such as amor, worse, orror, or in medium terms such as argumento, argoritmo, articulación I feel that the words are said as in French and not as a consonant in Spanish, it also happens in Spanish spain the same thing that I am raising the r phoneme

**Comment by rmcpantoja** [comment]
Hi @gregodejesus, 
Thank you for the suggested words. I just added them to this pull request.
However, the issue of phonemes is something in which I would like to encourage myself to improve, therefore I plan to read the documentation more often to see what we can do regarding both Latin American and Spanish (spain).
It should be added that the Spanish pronunciation can be a bit wrong in Espeak, but nevertheless, using tools like the phonemizer package in python is really great. For example, tacotron2 using phonemes or ForwardTacotron, both mentioned software are TTS in Spanish using this to improve speech quality.

**Comment by gregodejesus** [comment]
hi: where could I download the new es_dict file to test?

**Comment by rmcpantoja** [comment]
Hi @gregodejesus, 
Here's the compiled file with the changes:

**Comment by gregodejesus** [comment]
Hey. I was checking the es_dict file, I missed adding the word YouTube, i.e. the capital y word, and the capital T letter

**Comment by rmcpantoja** [comment]
Hi @gregodejesus, 
I've now set the prefix for capitalization on YouTube, hope that helps.
Also, to contribute you need to know about phonemes. I recommend reading the documentation of this repo.
Lastly, thanks again for your suggestions. Surely this would improve the pronunciation quality not only of espeak itself, but also backends that use espeak-ng as a phonemizer!

**Comment by gregodejesus** [comment]
if I read all the documentation, and of phonemes I also know, what I do not understand which programs are used or used for this purpose, it will not appear in the documentation note: I use windows.
other pronunciations: SSS=servicio social sustitutorio. SA=sociedad anónima. SM=su majestad. NB=nota bene. SAR=su alteza real. SNM=sobre el nivel del mar. NE=nordeste

**Comment by rmcpantoja** [comment]
Hi @gregodejesus 
You can use notepad or notepad++ on Windows without problems.
And once again, thank you for your contributions. I will add them soon. Also, I think that this PR it will be ready to merge once you add these next changes.

**Comment by rmcpantoja** [comment]
Hi.
Finally, this PR is ready to merge.
Now some of these improvements could improve reading through the espeak itself or using the phonemes backend.
Any opinion about it, @alex19EP and other collaborators?
Also, I'm also thinking of fixing a part of the sounds of some phonemes. This will not affect the phoneme backend, as it deals with sounds only.

**Comment by alex19EP** [comment]
hello @rmcpantoja i'll wait until i release a new stable release and then merge your pr.

**Comment by rmcpantoja** [comment]
Hi @alex19EP, 
I thought 1.52 would have these new changes, but that's ok. BTW, may I take this opportunity to ask if the new version will also be published in apt for Linux? Since the version hosted on it is 1.50+dfg6

**Pull request merged**
