### PR TITLE
Added Pyash constructed language to eSpeak

### PR DESCRIPTION
**Pull request by elspru**
Hi,

I added Pyash language to eSpeak,
though still having some problems with adding tone.
I removed it for now,
can make an issue to help figure it out.

Can find out more about the language at http://pyac.ca
though I've gotta update the website some.

Thanks,
Logan

### CODE REVIEW

**Comment by valdisvi** [comment]
Hi, @elspru!
I hesitate to include your pull request because:
1. Puash language seems just made up by you, because I couldn't find any reliable resource about it. Can you provide reliable information that this language is recognized and has correct code for it.
2. Changes in configuration files seems inconsistent, language code is sometimes shortened as _puac_, sometimes as _puash_ and there are also references to _lobjan_, which is different language (which has entry in wikipedia though).

**Comment by somebody1234** [comment]
https://www.academia.edu/34133204/Pyash_One_Language_to_Unite_Them_All
https://gitlab.com/liberit/pyac

**Comment by elspru** [comment]
Pyash is the English spelling, and pyac is the native spelling, the c is an 'sh' sound or /S/ just like in lojban.
I have a site for it pyac.ca that lists some of the papers written about it.
I'll be writing another one in a few months.
I'm currently in negotiations to have it used as an interlingua in translating Inuktitut.

But yeah feel free to hold off on adding it if the extra few KB is too much to add to espeak-ng. Can ask again when there are more users.

**Comment by elspru** [comment]
The current repo for pyac is lwonprom https://gitlab.com/liberit/lwonprom

**Comment by valdisvi** [comment]
@elspru, I merged your pull request as [new single commit](https://github.com/espeak-ng/espeak-ng/commit/dde072f6dc9805cd487e87132b56912762086b61).
Can you provide strings for checks also:
1. List of phonemes to check sounds for them. E.g. English at [tests/language-phonemes-test](https://github.com/espeak-ng/espeak-ng/blob/master/tests/language-phonemes.test#L53)
2. Some phrase (e.g. short [pangram](https://en.wikipedia.org/wiki/Pangram)), to check pronunciation rules. E.g. for English at [tests/language-pronunciation.test](https://github.com/espeak-ng/espeak-ng/blob/master/tests/language-pronunciation.test#L43).

**Pull request closed without merging**
