### PR TITLE
Fix Nepali

### PR DESCRIPTION
**Pull request by Andiv06**
I fixed the problem

### CODE REVIEW

**Review by Andiv06 — COMMENTED** [review]
We solved the problem with the lack //numbers in Nepali

**Comment by Andiv06** [comment]
We solved the problem with the lack of numbers in Nepali

**Comment by Andiv06** [comment]
We solved the problem with the lack of numbers in Nepali

**Comment by Andiv06** [comment]
We solved the problem with the lack of numbers in Nepali

**Comment by valdisvi** [comment]
Commit of this pull request has only comment added.

**Pull request closed without merging**
