### PR TITLE
Improve Japanese U

### PR DESCRIPTION
**Pull request by hozosch**
Based on what I heard by listening to natives speak, this is a more appropriate sound to use in my view.

### CODE REVIEW

**Comment by hozosch** [comment]
Still not all checks completed, but 12 successful! Phew! I declare this as completed on my side.

**Comment by hozosch** [comment]
Also tested it on odo.lv, works exactly as intended! Ready to be merged!

**Comment by hozosch** [comment]
Will this one be merged? I'm sorry if it violates something it shouldn't.

**Comment by valdisvi** [comment]
This is merged into project as single commit 0954b24c8ca47aa834c31144c119c14c85f1a52a

**Pull request closed without merging**
