### PR TITLE
German: fixed the words balance, behilflich and garage

### PR DESCRIPTION
**Pull request by Sur3**
I did some major improvements to the words balance and garage and a minor improvement to the word behilflich.
This pull request supersedes the pull request https://github.com/espeak-ng/espeak-ng/pull/1875 as my pronunciation of the word garage sounds more natural.

### CODE REVIEW

**Comment by hozosch** [comment]
In my opinion, in the case of  "Garage", a simple "$alt" would have sufficed. With balance, I would have preferred the proper French pronunciation, the A~ phoneme is existing in the German phoneme set. As for behilflich, I honestly can't see how that is an improvement. In my view, you made it worse. I totally get the other two words though.

**Comment by Sur3** [comment]
> In my opinion, in the case of "Garage", a simple "$alt" would have sufficed.

Yes $alt sounds fine aswell as this gives [[gaR'A:Z@]] which is pretty similar to [[gaR'AZ@]]. I still prefer my version though, but this is not a huge difference, is there any computational benefit from using just $alt instead?

> With balance, I would have preferred the proper French pronunciation

I intentionally chose the German pronunciation as this is for the German language. Speaking Germanized words in their original languages pronunciation is correct aswell, but not specific for the German language.

> As for behilflich, I honestly can't see how that is an improvement. In my view, you made it worse and the pronunciation as it was sounds already perfect. I totally get the other two words though.

It is hard to catch but if you listen to a complete sentence like "Kann ich [[b@h'IlflIC]] sein? Kann ich [[byh'Ilf-liC]] sein?" you can here the improvement. The first form sounds more like behelflich while mine sounds like behilflich, though my form is still not perfect, I would have prefered a sound between @ and y for the first syllable, but I didn't know how to produce that.

**Comment by hozosch** [comment]
This is the trouble with such things, there's a lot of subjectivity going on here. I still don't see how this improves the word "behilflich". What strikes me as particularly strange is how you used "y" instead of "@" and "liC" instead of "lIC". By the way, the dash you put in doesn't have any effect, from what I can tell anyway. As for $alt having any computing benifit, maybe someone like @rhdunn knows more about this. My guess is that there isn't and it just makes it easier to correct some words, in that you don't have to type as much.

**Comment by Sur3** [comment]
> What strikes me as particularly strange is how you used "y" instead of "@"
I found @ too be to short to make out the proper "be", and somehow it also influences the pronunciation of the next syllable to sound more like hilf. Ideally I woud like to find a better version of i for the second syllable though. You said A~ phoneme exists in the German phoneme set, is there a list of the phonemes so I can try a different vovel for the second syllable?
The difference between "liC" and "lIC" seems minor, I just found the word sounds clearer and more polite with the uppercase I.

**Comment by hozosch** [comment]
Ok, as for @ being too short, this is something which should be fixed in the "PH-German" file. The length that's currently used for ends of words should be used in all cases. This simply requires a few lines to be deleted in the phoneme definition of @. It was me who changed this some time ago, but I see now how this is problematic.  As for a different I, this would need to be added. I, myself, can't make out what you do though, about the pronunciation sounding more like "e" with the way as it was before your improvement. It sounds fine, apart from that @ which is too short.

**Comment by hozosch** [comment]
And you probably meant that the "lich" sounds clearer and more polite with the lower case i, not the upper case one. To me though, the lower case one sounds foreign and not as part of normal German pronunciation.

**Comment by Sur3** [comment]
> Ok, as for @ being too short, this is something which should be fixed in the "PH-German" file. The length that's currently used for ends of words should be used in all cases. This simply requires a few lines to be deleted in the phoneme definition of @. It was me who changed this some time ago, but I see now how this is problematic.

I can see use in the shorter @ aswell. So cant we just add some modifier ( : colon length modifier seems to not really work for @ and it also doesn't work for I? ) or a new phoneme? I think a sound between e and @ would be ideal for the first syllable.

> As for a different I, this would need to be added. I, myself, can't make out what you do though, about the pronunciation sounding more like "e" with the way as it was before your improvement. It sounds fine, apart from that @ which is too short.

The second syllable really sounds horrible, I always understand "behölflich" instead of "behilflich", are you maybe from eastern Germany? The sound should be more between ü and i but closer to i instead of sounding like something between ö and e.
Removing the ' from the second syllable with lower case i [[[[b@hilflIC]]]] somehow fixes it, but then the accent moves to the last syllable which then sounds too long.

> And you probably meant that the "lich" sounds clearer and more polite with the lower case i, not the upper case one. To me though, the lower case one sounds foreign and not as part of normal German pronunciation.

Yes i meant lower case, but this is really a minor difference, so I'm fine with upper case aswell.

**Comment by hozosch** [comment]
No, I'm not from eastern Germany, I'm originaly from Koblenz. I do have a lot of  influence from one of my friends from eastern Germany though, whith whom I still live together to this day, so this may play a part. But even before that, I never found this word to be a problem. I still don't change my mind about the second syllable. I also know though that ESpeak is known for sounding incomprehensive and unpleasant, so I suggest using another speech synth, or use ESpeak with MBrola, which should sound much more natural. That's what I suggest anyway. Because as of now, I don't have an idea that satisfies both our needs. We both seem to have strong disagreements when it comes to that word. I'm sorry if I sounded harsh but I'm currently lost.

**Comment by Sur3** [comment]
> use ESpeak with MBrola, which should sound much more natural.

I am already using the mbrola-voices, maybe that is part of our disagreement then.

Regarding the short @ i checked some other words aswell and basically every word beginning with be- sounds too short, so as you already said fixing this in the phonemes instead of the exception list sounds like the way to go.

Maybe we can figure out the second syllable afterwards, when it still sounds bad, as the other syllables seem to influence the overall sound, fixing the first might already be enough to make it sound okaish. Meanwhile I can remove the word from this pull request.

**Comment by hozosch** [comment]
Which of the voices are you using? I tested male 2 and male 6 on odo.lv/espeak and they sound fine to me too. I unfortunately can't do the phoneme fix yet, because there's still an open pull request with some variants, and I don't want this to become mixed up. Do you think you can have a look? I think the code is pretty straightforward and very understandable for someone who knows some linguistics and not much programming.

**Comment by Sur3** [comment]
Yes, de2 and de6 sound indeed better. I am using de5 which is a female voice, the second syllable sounds quite different there. 

> Do you think you can have a look?

Where exactly?

**Comment by hozosch** [comment]
Yeah, I get it now. It's sort of like "behöhlflich" or something. I'm beginning to think of things that are out of my capabilities, like working on that voice itself, or more precisely, at its phoneme translation file. The source code for those is in the "mbrola" folder in "PHSource". There's actually something I did once, which may play a part in that as well. I changed the stress length in those voices, because the vowels sounded all too short without those and it sounded really horrible. But this may have had some negative side effects as well. I wish there were a way to change phoneme duration in those phoneme translation files for MBrola, then there shouldn't be a problem. I think, what it is, is that the l seems too long, but that's only my personal feeling. I mostly use ESpeak without MBrola, and iven4. Mostly my modified 1.48.15, the original eSpeak for sapi5 on Windows, because it's very easy to make changes with Espeakedit and test them right on the fly with NVDA, my screen reader. I don't think those modifications would be liked by most people, so I just use them on my own. And compiling Espeak-ng to use my modifications with the built-in driver for NVDA is something I didn't work out how to do yet.

**Comment by Sur3** [comment]
Weird only the male voices seem to have subfolders in phsource/mbrola/
Are female voices not supported or to the use the corresponding male voice folder?

**Comment by hozosch** [comment]
Yes, they do. I just had a look. De5 and de7 use de6_phtrans and de 3 and de1 use de2_phtrans. But the phtrans files are the compiled ones, you need to modify them like I described in my previous comment. Btw, these are not folders, they are files without extensions. Just open them with a text editor. Unfrotunately, with those files, you have to confirm that every time.

**Comment by Sur3** [comment]
I found some corresponding comments in the phsource/mbrola/de6 file:

**Comment by Sur3** [comment]
I found a fix for the I sound by using 5% i: in front of the I, the problem is that replaces I everywhere, I tried to match for stressed syllables `'I` only, but espeak-ng seems to ignore that:
`34 I '   5  i: I`

**Comment by Sur3** [comment]
Ok I managed to fix the de6 file to produce better `h'I` sound by using 10% `i:`
and better b@ sound by using 40% `e:` but the b@ is still a bit short.

**Comment by Sur3** [comment]
Ideally my corrected b@ would be used for words as "Bett" aswell, But then this would have to be changed for every German Language file, but the word Bett sounds pretty weird in all German Language files currently anyway because the correct vowel is not represented ( https://en.wikipedia.org/wiki/Mid_front_unrounded_vowel ). It would be nice if we could have a separate phoneme for that like `@:` or some other syntax so we can pronounce words like "Bett" correctly.

**Comment by hozosch** [comment]
Oh, I received one comment by email which you seemed to have deleted, because I can't see it anymore. It was about the word "bett". I really can't se a problem with that one, not even with de5, although I got to say that de5 is probably the strangest sounding voice of the German Mbrola voices. I tend to stick to de2 or de6, sometimes de4 as well, although ESpeak really doesn't have good support for these voices in any case. As for the longer @, you need to change the PH-German file in the phsource folder. in the phoneme definition for !@", there is this if clause saying "If thisPh(isWordEnd)" or something like that. Get rid of it completely and change the main length from 40 to 120. That is the length that was originally used before I made changes to it, and it is fine like this I think. Another thing, have you also noticed how "r" sounds so bad, for example where r is used kind of like a vowel, such as in words like the number 4, or Uhr? I would know how to fix this, which, in my view, would also improve ESpeak's sound in general, but it's very likely that quite a number of people would think otherwise.

**Comment by Sur3** [comment]
Yeah I deleted the comment about Bett again, because I thought it was a bit offtopic and there are more urgent issues, but yeah I don't think the word Bett sounds good in mb-de2 or other voices. Right I also had some problems with r, but they were of different nature; The problem with words like Uhr and almost all other words ending in :r is that there should be no r at all, Uhr is more pronounced like [['u:@]] maybe something in between @ and r would be nice, similar to what I did with b@ and h'I there could be a definition for replacing r with 90% @ and 10% r at word endings when preceded by an u: or something similar.
I didn't test this but the phsource file could look somewhat like this:
`64 r u: 90  @ r`

**Comment by hozosch** [comment]
Yes, I know what you mean about r. Like I said, I have a method to improve it, but I'm not sure if this will be accepted by most people. I know this is offtopic, but I'm really asking myself what sounds wrong about "bett". This is something where I really cannot see what should be wrong about that, not even with de5.

**Comment by hozosch** [comment]
In espeak-ng-data/voices/mb, all voice files declare which database and phoneme translation file they use. From that, I remembered it.

**Pull request merged**
