### PR TITLE
Applied Klatt fixes from NV Access and added Edward variant.

### PR DESCRIPTION
**Pull request by datajake1999**

### CODE REVIEW

**Comment by datajake1999** [comment]
I found this code at https://bitbucket.org/nvaccess/espeak/src/klatt5/ and ported it to eSpeak NG. I also added the Edward variant.
These fixes make Klatt voices sound less distorted and adds a new Klatt5 voice. I am attaching an archive of samples comparing the old and new code.
[klatt_samples.zip](https://github.com/espeak-ng/espeak-ng/files/5579587/klatt_samples.zip)

**Comment by hozosch** [comment]
Hmmm, this doesn't sound quite like speech player in espeak, but yes, it does sound better.

**Comment by datajake1999** [comment]
This is a more portable solution since speechPlayer depends on some Windows things. I think this will make a lot of people happy since it sounds better than the older Klatt code, and many people complained about the distorted audio. As a side note, I find it interesting that Klatt3 can sound different depending on how the code is built. I used eSpeak 1.48.15 to generate these samples when I was investigating these fixes several months ago. I think I used  a different version of visual studio to build the library I used to demonstrate the fixes, so that is why the audio demonstrating the fix for klatt3 sounds distorted while the old version sounds less distorted. I am currently testing these fixes with NVDA, and klatt3 doesn't distort.

**Comment by hozosch** [comment]
Well you've got a point there. I like klatt 5 best. I'd love to test it with NVDA myself.

**Comment by hozosch** [comment]
One thing which still bothers me, in comparison with speech player, is this slight roughness.

**Comment by valdisvi** [comment]
Thanks for contribution!
Your pull request is merged with updated test for Klatt voices as well.

**Pull request merged**
