### PR TITLE
Updated phonetics and stress rules for Basque

### PR DESCRIPTION
**Pull request by agonzalezd**
Updated some phonetic changes in eu_list and eu_rules.

Added stress rule in dictionary.c

### CODE REVIEW

**Comment by jaacoppi** [comment]
Could you add two more commits:
1) update the test in tests/language-pronunciation.test (run make check for full test suite or tests/language-pronunciation.test for the single test)
2) use "stressRule 15" in espeak-ng-data/lang/eu instead of the stress_rule in tr_languages.c. See docs(voices.md for more information. Sorry I missed this part when originally giving you instructions. We prefer the user configurable settings in espeak-ng-data/lang instead of hard coded values in the codebase.

**Comment by jaacoppi** [comment]
for the "ez sait" problem, see if $combine documented in docs/dictionary.md helps.

**Comment by agonzalezd** [comment]
I am having an error with `ssml.test`:

```
testing <prosody>
1c1
< fcb28f00670959980038171ceda3c6bdec61b884
---
> 5ea0dcd3dc9682adacebcaf3d2fa6c8d6fa6e4aa
make: *** [Makefile:2863: tests/ssml.check] Error 1
```

**Comment by hozosch** [comment]
Yes. So the error message's saying that, in the SSML test, the line:
< fcb28f00670959980038171ceda3c6bdec61b884
Should be replaced with
> 5ea0dcd3dc9682adacebcaf3d2fa6c8d6fa6e4aa
This is the so called hashsum, which always changes when editing pronunciation rules or phoneme definitions

**Comment by jaacoppi** [comment]
Some tests (ssml, klatt, translate.test) produce different results with different compilers. Just run tests/language-pronunciation.test for now.

**Pull request closed without merging**
