### PR TITLE
several exception words and an unknown  charactor added.

### PR DESCRIPTION
**Pull request by shadyar**

### CODE REVIEW

**Comment by jaacoppi** [comment]
Thanks for the commit.

Note about git:
I did `git merge` but didn't notice the message:
Fast-forward (no commit created; -m option ignored)
That's why there's no "Merge pull request #899" message. I'm not sure if this is a problem or not.

So far all merges I've done have created the commit message.  Should I have used --no-ff?

**Comment by valdisvi** [comment]
I checkout pull request into new local branch and after checks merge branch into master branch.

**Comment by shadyar** [comment]
@valdisvi
Thanks so much. Is there some thing I should do about this issue?

**Comment by valdisvi** [comment]
No. That was info for @jaacoppi.

**Pull request merged**
