### PR TITLE
Use deterministic random generator

### LINKED ISSUE #1528: Use deterministic random generator
There is some calls for `rand()`. I propose to replace it with some deterministic, platform-independent and thread (context) safe PRNG. It will add an ability to test reproducibility of voice-specific audio generation (with breath attributes, e.g.)

### PR DESCRIPTION
**Pull request by djphoenix**
Fixes #1528 

Now, `klatt` and `breath`-enabled variants may be added to tests

### CODE REVIEW

**Comment by djphoenix** [comment]
That was tricky a bit, but also fixed a several bugs that found in klatt.c, thanks to sanitizers.

**Comment by djphoenix** [comment]
@sthibaul @jaacoppi since 7 year old code was touched, I really want you both to review it, please.

**Comment by sthibaul** [comment]
Well, I don't know this code at all either.

**Comment by djphoenix** [comment]
@sthibaul I think, that question is not about "do you know this code", I really assume no, its 7 years old, it sometimes hard to remember why I wrote something yesterday, hah.

The main question is - does that changes seems logically right? Does it contains some that may become an issue in future?

**Review by jaacoppi — CHANGES_REQUESTED** [review]
I don't understand RNG enouogh to comment. Do the added tests now prove that this code is better than the original, i.e. produce same results for each platform?

Two change requests for code readability:

1) deterministic should be bool instead of int.

2) This is now a single commit that includes changes to many places. Please separate it to smaller pieces and document the idea behind each commit.

I think a logical separation would be:
* test
* functions for rng
* setting the CLI parameter

You can think of a better solution.

P.S.
Do we have API documentation somewhere? If yes, do the new functions need to be documented there? If not, I think we need it.

**Comment by djphoenix** [comment]
> Do the added tests now prove that this code is better than the original, i.e. produce same results for each platform?

Of course, at least for macOS and Ubuntu on CI, and some dockered systems that I have, results are the same for klatt/breath voices that use randomness.

I agree with requested changes, will clean up today.

**Pull request merged**
