### PR TITLE
singing synthesis

### PR DESCRIPTION
**Pull request by tplaten**
I've written a patch for eSpeak-NG which allows singing synthesis using an external program.

### CODE REVIEW

**Comment by The1Freeman** [comment]
This could be interesting if it didn't have the UTAU requirement

**Comment by valdisvi** [comment]
@tplaten, can you also add description of switches and command examples, how to use (and test it) in [speak-ng.1.ronn](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn) file?

**Comment by tplaten** [comment]
There is no UTAU requirement, any UTAU compatible synth, such as Cadencii or Utsu can be used for singing synthesis.

**Comment by tplaten** [comment]
To test singing synthesis one has to specify the frequency or midi note number of the note to be sung. The commands to control an external program are written to stdout.

**Comment by The1Freeman** [comment]
Maybe it makes sense to have an example of a VST/LADSPA plugin attached that acts as a bridge?

**Comment by tplaten** [comment]
Yes this could be implemented as a VST/LADSPA plugin. But I have written a DAW called QTAU which has its own plugin interface. My patch is mostly based on [How to make eSpeak sing](https://www.youtube.com/watch?v=UTu5fP0lrjY), but I've added the WCMD_OTO stuff. I created a Czech [Demo Song](https://ia801503.us.archive.org/20/items/ten_suchdolsky_rybnik_espeak_vosamp/ten_suchdolsky_rybnik_espeak_vosamp.ogg) using QTAU.

**Comment by tplaten** [comment]
@valdisvi, I've added a description of switches in espeak-ng.1.ronn.

**Comment by valdisvi** [comment]
As Eric S. Raymond said, "Any tool should be useful in the expected way, but a truly great tool lends itself to uses you never expected". I'm glad you could use eSpeak NG for your tricky problem.
But I hesitate to add proposed complexity into the main project. It would be much better, if input parameters could set actual frequency and length of the phrase and provide something like manageable [MBROLA](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md) [input](https://github.com/numediart/MBROLA/#phoneme-commands) as an output, because that could could be usable (probably with simple transformations) for other (preferably, open source) speech synthesis tools.
Maybe @rhdunn can also comment on this.

**Comment by tplaten** [comment]
The patch keeps most of the complexity outside of espeak-ng. As an example the MusicXML parsing is not done by espeak-ng but by [Sinsy](https://github.com/r9y9/sinsy). Sinsy will then invoke espeak-ng for each note with a parameters that set the frequency and the note velocity. In the last step an external [NU-MBROLA](https://pdfs.semanticscholar.org/c6cd/7f3e002852c32a9cdb04bff74deb04fbc264.pdf) instance will change the length of the phrase.

**Comment by valdisvi** [comment]
@tplaten, proper way to do this would be passing [SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html) to the espeak-ng. SSML is [partially implemented](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/ssml.c), but it is incomplete (and can't be implemented well with current approach). I encourage you to review (and update) new [eSpeak NG Roadmap](https://github.com/espeak-ng/espeak-ng/wiki/eSpeak-NG-roadmap) and work on that.

**Comment by tplaten** [comment]
I don't think that SSML will work for singing very well. The codebase is too complex and to hard to maintain. Maybe I'll do a rewrite in a different language such as python, which handles unicode natively. I've already worked on an MBROLA rewrite in C++ half a year before MBROLA source code was published.

**Pull request closed without merging**
