### PR TITLE
Support for Xextan Language

### PR DESCRIPTION
**Pull request by WallFlowerWeed**
Data for the constructed art language Xextan, adapted for current version of eSpeak-NG.

### CODE REVIEW

**Comment by jaacoppi** [comment]
Looks good. Things to do before approval:

    add a commit to update ChangeLog.md to include this new language
    update your branch to solve the "This branch is out-of-date with the base branch" warning.

**Comment by jaacoppi** [comment]
Also: include the language in the windows build files in src/windows as well

**Comment by WallFlowerWeed** [comment]
I believe the branch is ready for inspection. Do let me know if I've missed anything.

**Comment by WallFlowerWeed** [comment]
I've added a phoneme test for Xextan, which should hopefully resolve all the failed checks.

**Comment by WallFlowerWeed** [comment]
I've added a appropriate phoneme test for Xextan, which should hopefully resolve the failed checks.

**Comment by WallFlowerWeed** [comment]
My apologies! I seemed to have fumbled my phone and accidentally closed the pull request for a minute.

**Comment by WallFlowerWeed** [comment]
In any case, the five checks that failed the last time around seem to have been inherited from the main branch.

**Comment by jaacoppi** [comment]
Can you do one more rebase for your branch? Unfortunately for you, this was the last PR of the three incoming new languages

**Comment by WallFlowerWeed** [comment]
Done.

**Pull request merged**
