### PR TITLE
improve syllabic m and n

### PR DESCRIPTION
**Pull request by hozosch**

### CODE REVIEW

**Comment by alex19EP** [comment]
hmm. perhaps it would be better to run the tests locally?

**Comment by hozosch** [comment]
Don't know how to do this and I don't want to do something that may be very fiddly.

**Comment by alex19EP** [comment]
you need to reduce the number of commits.

**Comment by valdisvi** [comment]
I merged it as squashed commit: b6ffccff6a470f53139e82ffefe937fa57e06c0e

**Pull request closed without merging**
