### PR TITLE
Please review, how to check of actual wav files instead of hashes

### PR DESCRIPTION
**Pull request by valdisvi**
Provided changes use sox (and bc for float number calculation) to mix inverted reference *.wav file with actually produced *.wav file. In normal situation it produces just silence (with some digitization/generation noise).
Was tested, that, if some one phoneme is changed, it causes enough difference to make sound in mixed file which causes significant increase in root mean square amplitude of produced file.
Works with the same speed as calculation of hashes, but takes more disk space for wav files (43MB for phoneme tests). 
With more awk/bash tricks, we can get rid of bc to compare numbers (I don't know is worth effort).
If it is ok, I'll implement it for language pronunciation tests.

### CODE REVIEW

**Comment by rhdunn** [comment]
What advantage does this give compared with the hash approach? The reason I chose to use hases is that it does not take up a large amount of space, and is easy to see in things like automated builds.

The intention of the tests is to make sure the output remains identical unless it has been specifically changed, even if that change is low-level noise.

**Comment by valdisvi** [comment]
Comparison of *.wav files would do greater benefit for [language pronunciation test](https://github.com/espeak-ng/espeak-ng/blob/master/tests/language-pronunciation.test). I assume, with this we could catch regressions like [letterVowel](919f3240cbbb8060da550f0f9641e69b2975d9f4) or [replacement](424f705525e73fcdc988af8db6cc32d104e648e6) earlier. But it will take even more disk space for reference *.wav files...

**Comment by rhdunn** [comment]
I'm not sure what benefit this would have for the language pronunciation tests -- those are testing the letter to phoneme rules, not the phoneme to audio generation. The only benefit I could see is in testing tone and stress, but those should be separate tests as you can then tailor those tests to check the stress and tone patterns of the language (e.g. using the different words from Chinese that are pronounced "ma" with different stresses) -- maybe `language-stress.test` and `language-tone.test` files that would check both pronunciation and audio hash.

Regarding the letterVowel regression, I tested that with just the pronunciation output (`-x`) for the words in that issue. This change would not pick up that unless the rules for "is this word pronouncible" are called (e.g. with words like "sky" in English).

Ideally, there should be a separate set of tests to cover the language rules. These should use both audio hashes (for things like tone and stress that affect the audio) and pronunciation output (for things like the letter vowels and replacement characters). They should also check the different voice files, which inherit the language rules.

I have also started a separate set of tests for cardinal and ordinal numbers, which should be extended to provide coverage of the different languages.

It is easier to see what is going on with the pronunciation output checks. Especially on remote builds like the Travis continuous integration server. Ideally, tests like the replacement characters and script to script (e.g. Latin to Cyrillic) should check the replaced text, but espeak does not currently have a way to output that.

I also don't like the idea of adding megabytes of data just for the tests, especially when that is likely to change.

**Comment by valdisvi** [comment]
OK

**Pull request closed without merging**
