### PR TITLE
Test & fix for #824

### PR DESCRIPTION
**Pull request by jaacoppi**

### CODE REVIEW

**Comment by valdisvi** [comment]
Merged in project, but I rewrote commit e5c62b2 to 30214437 where `a#` are replaced with `a` for expected output.

**Comment by jaacoppi** [comment]
Thanks. Yet another corrupted build environment on my machine.

**Comment by jaacoppi** [comment]
Actually.. on my machine  e5c62b2 wroks but 3021443 fails. This is strange.

**Comment by jaacoppi** [comment]
espeak-ng 1.50 installed on Arch also fails the test in 3021443.

**Pull request closed without merging**
