### PR TITLE
Adding Crimean Tatar language

### PR DESCRIPTION
**Pull request by Andiv2006**

### CODE REVIEW

**Review by Andiv2006 — COMMENTED** [review]
I added Crimean Tatar language

**Comment by sthibaul** [comment]
Please see the build failures:
```
ph_crimean_tatar(81): Keyword 'phoneme' expected
ph_crimean_tatar(82): Keyword 'phoneme' expected
ph_crimean_tatar(82): Keyword 'phoneme' expected
ph_crimean_tatar(83): Keyword 'phoneme' expected
ph_crimean_tatar(84): The phoneme feature is not recognised: 'l'.
ph_crimean_tatar(85): a phoneme type or manner of articulation must be specified before endtype
```

**Comment by sthibaul** [comment]
Please do try to build your changes, see:
```
Compiling: 'crh_rules'
   77: Bad phoneme [ı] (U+131) in:  .group ı

   77: Wrong initial letters '.group' for group 'h'
   78: Wrong initial letters 'ı' for group 'h'
   80: Wrong initial letters '.group' for group 'h'
   81: Wrong initial letters 'i' for group 'h'
   83: Wrong initial letters '.group' for group 'h'
   84: Wrong initial letters 'j' for group 'h'
   86: Wrong initial letters '.group' for group 'h'
   87: Wrong initial letters 'k' for group 'h'
   88: Wrong initial letters 'kk' for group 'h'
   90: Wrong initial letters '.group' for group 'h'
   91: Wrong initial letters 'l' for group 'h'
   92: Letter group L02 not defined
   92: Wrong initial letters 'l' for group 'h'
   93: Letter group L02 not defined
   93: Wrong initial letters 'l' for group 'h'
  140: Bad phoneme [y] (U+79) in:  .group y

  140: Wrong initial letters '.group' for group 'v'
  141: Bad phoneme [y] (U+79) in:          y         y

  141: Wrong initial letters 'y' for group 'v'
  143: Wrong initial letters '.group' for group 'v'
  144: Wrong initial letters 'z' for group 'v'
  146: Wrong initial letters '.group' for group 'v'
  147: Wrong initial letters '$' for group 'v'
	51 rules, 25 groups (0)

Error: Compile error.
```

**Comment by 0x5066** [comment]
"Unable to have Danish numbers for...
....greenlandic language (Pay attention! do not try to editing this file without my permission too!)"
From that commit alone it's clear he's not interested in collaborating and I'd generally say that's a troll, if possible this person and any alt accounts created should be blocked, which unfortunately adds some moderation to this.

**Comment by alex19EP** [comment]
I fully agree. maybe he isn't trolling but here is definitely some kind of communication barrier and @Andiv2006 made no effort to overcome this barrier.

@jaacoppi what do you think?

**Comment by jaacoppi** [comment]
I have now blocked @Andiv2006. Reason is spamming multiple pull requests and not taking part in the discussions about those PRs.

**Pull request closed without merging**
