### PR TITLE
Rule alignment fixes for non compliant platforms / Fix for emscripten demo

### PR DESCRIPTION
**Pull request by BenTalagan**
This is a fix for #584, but the PR scope may be potentially larger : without this fix, the handling of compiled rules is not guaranteed to be compliant across platforms, since casting to int* may happen on non aligned char* , which has to be avoided.

Some minor options also have to be added to the emscripten compilation workflow to make it work again with newer versions.

### CODE REVIEW

**Comment by BenTalagan** [comment]
Hum, checks failed, but I've verified locally and it looks like that they were already broken before these changes. Is it normal?

**Comment by rhdunn** [comment]
They are passing on the master branch. The failing test is https://travis-ci.org/espeak-ng/espeak-ng/jobs/613903437#L2232.

**Comment by BenTalagan** [comment]
Pheew! I really need some rest, you saved me from pushing some really silly code.  Looks better now.

**Comment by rhdunn** [comment]
That's what tests are for :).

Thanks for the fix.

**Pull request merged**
