### PR TITLE
stressLength and stressAmp moved to configuration file for all languages, improvements for several languages

### PR DESCRIPTION
**Pull request by valdisvi**
If stressLength or stressAmp is not set, it will be set by Translator *NewTranslator(void).
Plus some other fixes/comments for found issues.

### CODE REVIEW

**Comment by rhdunn** [comment]
The voice files (MBROLA voices, and the voice variants) need to be handled as well. That way, they get the correct default settings.

I'm thinking something like `import lang/gmw/en`, with the import looking from the espeak data directory, or `importLanguage en` with the imported file being searched for in the `lang` directory of the espeak data directory. Using `import` would allow a language/voice to refine another. If `importLanguage` seems the better option, it may be simpler to make the `language fr` command do the import if the filename is not the current file (although this would make it harder for the accents to inherit from the main language).

For now, `import lang/gmw/en` looks like the best option, as it gives the most flexibility. If more specific functionality is useful, it can be created later.

**Comment by valdisvi** [comment]
Oh, I didn't know about this. Will you merge this and solve Mbrola voices yourself?

**Comment by rhdunn** [comment]
Yes. I can look at solving the MBROLA voices, then merge this.

**Comment by valdisvi** [comment]
Reece, as a temporary workaround I added stressLength, stressAmp and stressAdd in [this commit](https://github.com/espeak-ng/espeak-ng/pull/363/commits/e0ec1df29e26dde37e5d8798bd610f039ce6cc7a), which you will be able to revert, when done with nicer solution.

**Comment by valdisvi** [comment]
I made merge from upstream and will make cleaner pull request again.

**Pull request closed without merging**
