### PR TITLE
Correct strcpy calling issues when compiling data on OS X.

### PR DESCRIPTION
**Pull request by ragb**

### CODE REVIEW

**Comment by rhdunn** [comment]
The semaphore fix is causing the dictionary compilation to hang (e.g. building `af` during the build). I have merged the strcpy fix -- thanks!

**Comment by ragb** [comment]
You’re right, didn’t do a `make clean` so didn’t catch it. This won’t be trivial but I’ll try. haven’t touched this kind of code for a while, let’s see what I can do.

This commit was not suposed to go to the PR but I forgot this branch was associated with it, sorry.

**Comment by rhdunn** [comment]
No problem. I'll merge the changes if/when you do figure out what the problem is.

**Comment by ragb** [comment]
Ok, found the problem, not sure if there are others but at least data compiles.

event.c logic is truly more complex, wil try that one…

**Comment by rhdunn** [comment]
Let me know when you are happy with these changes and I'll merge them. I have done some testing on the current version and have not noticed any issues so far.

**Comment by ragb** [comment]
Ok, thanks. Honestly I can’t test this properly on Os X due to no direct audio support, but it seems to run nicely when generating wave files (not completly sure if it is using the async api in this case).

**Comment by rhdunn** [comment]
I've tried with using the async API (e.g. `espeak-ng -f FILE`) and the output to speakers sounds fine (I haven't had any hangs with the code). Thanks for the OSX compatibility changes.

**Pull request merged**
