### PR TITLE
Update Hebrew rules

### PR DESCRIPTION
**Pull request by omeritzics**
Added plural Nikud-less rules and replaced the sound of letter Reish/ר (R instead of Q"), along to other fixes.

### CODE REVIEW

**Comment by sthibaul** [comment]
Please see the check failures.

**Comment by omeritzics** [comment]
> Please see and fix the check failures.

I have no idea what it could be. I didn't change something in the code, just the pronounciation rules.

**Comment by omeritzics** [comment]
Maybe the repo isn't synced. I'm going to update the branch, but I need someone to start the checks before the main repo gets changed again

**Comment by sthibaul** [comment]
> I have no idea what it could be. I didn't change something in the code, just the pronounciation rules.

See the build log, very notably at the end:

```
144: Bad phoneme [y] (U+79) in: ים  'yam
149: Bad phoneme [y] (U+79) in: יום  yom
```
```
262: Wrong initial letters 'ים' for group 'ם'
263: Wrong initial letters 'ום' for group 'ם'
```

**Comment by omeritzics** [comment]
> > I have no idea what it could be. I didn't change something in the code, just the pronounciation rules.
> 
> See the build log, very notably at the end:
> 
> ```
> 144: Bad phoneme [y] (U+79) in: ים  'yam
> 149: Bad phoneme [y] (U+79) in: יום  yom
> ```
> 
> ```
> 262: Wrong initial letters 'ים' for group 'ם'
> 263: Wrong initial letters 'ום' for group 'ם'
> ```

Thank you for getting me noticed :)
Now it is all fixed.

**Comment by sthibaul** [comment]
There is still
```
   262: Wrong initial letters 'ים' for group 'ם'
  263: Wrong initial letters 'ום' for group 'ם'
```

**Comment by omeritzics** [comment]
Hope it is now fixed, thank you for the assistance :)

**Pull request merged**
