### PR TITLE
Fix errors and sending pull request again ( Shan language )

### PR DESCRIPTION
**Pull request by ronaldaug**
Please don't merge the previous one here -> [https://github.com/espeak-ng/espeak-ng/pull/541](https://github.com/espeak-ng/espeak-ng/pull/541)

This is a new pull request from my forked repo.

1 - Fixed tone marks 1 and 4; 
2 - Added 3 more vowels `(        ွ      ,        ို      ,        ိူ      )`
3 - Added large numbers until  1xxxx

This is the correct one, Thanks in advance.

### CODE REVIEW

**Comment by valdisvi** [comment]
@ronaldaug, if you will change `tests/language-phonemes.test` file line from:

```
test_lang shn e568aca66c2f58fdaf5dda8a67f4d21f05710234 "ma na Ja Na pa p_ha ba ta t_ha da ka k_ha ga ?a fa sa za Ta ha tS;a Ra ja wa la _:_ mi mI mW mu me m@ mo mE ma ma: mO miu meu mEu mau ma:u mWi mui m@i moi mai ma:i mOi maW _:_ ma1 ma2 ma3 ma4 ma5 ma6"
```
to
```
test_lang shn 0ba8e83b668e71d174e07e557f3d0be82d2f1073 "ma na Ja Na pa p_ha ba ta t_ha da ka k_ha ga ?a fa sa za Ta ha tS;a Ra ja wa la _:_ mi mI mW mu me m@ mo mE ma ma: mO miu meu mEu mau ma:u mWi mui m@i moi mai ma:i mOi maW _:_ ma1 ma2 ma3 ma4 ma5 ma6"
```
unit tests will pass.
This is due to changed definitions of vowels.

**Comment by ronaldaug** [comment]
Thanks @valdisvi I have changed it.
I don't see any differences in these two lines. (Only the id numbers is different)

**Comment by valdisvi** [comment]
@ronaldaug, besides currently having conflict for `dictsource/shn_list` file, this pull request has bad commit 3f995bd48e4cfc4d9157073d12806b92e29153a2, which has too many files are unnecessarily changed.
I could just create new commit with your changes, but I'm not sure, what to do with differences from espeak-ng to your project. E.g. for shn_rules file (differences between your project and espeak-ng):

```
1c1
< // Shan (Tai Yai) pronunciation rules (Shan script)
---
> // Shan (Tai Yay) pronunciation rules (Burmese script)
95a96
>       ေ)ႃ     O
105c106
<          _)   ဵ (_      e
---
>               ဵ          e
119,121c120
< 
< .group  ေႃ
<             ေႃ    O   // in group with other characters if necessary
---
>     _)  ေႃ    O   // in group with other characters if necessary
123,130d121
< .group     ို
<             _)  ို(_    W
< 		  	  
< .group      ိူ
<            _)   ိူ (_    @ 
< 		  
< .group      ွ
<                 ွ        O
200c191,192
< // Six tone marks ( 1 is empty )
---
> .group  း
>              း      1 // FIXME there should be more proper rules for this
207,209d198
< 		 
< .group  း
<              း      4 // FIXME there should be more proper rules for this
213c202
< 			 
---
> 
215,216c204,205
<              ႊ      6
< 	
---
>              ႊ      5
> 
223c212
< .group  // all other symbols, if necessary
```
Also check your git user data. Your name and surname looks strange in commits.

**Comment by ronaldaug** [comment]
Sorry for making bad pull requests. 
Last year I didn't know how **git** actually work. 
And I'm going to contribute on SHAN language again. 
Thanks @valdisvi

**Pull request closed without merging**
