### PR TITLE
Update Arabic

### PR DESCRIPTION
**Pull request by Andiv06**

### CODE REVIEW

**Comment by king-dahmanus** [comment]
what is new in this, can you please elaborate? I, for some reason, can't see the log in the commit

**Comment by king-dahmanus** [comment]
I checked, and impressive work, you tried to improve the numbers. However, some numbers, mainly the milj'a:R side of things, otherwise known as the billions, are not correct, they have the small r which produces an english r, where there should be an R capital to do a more correct arabic rolled r. Also, please recommit this one after making sure that every a after a q, R, s[, gH, x/X is followed by a period, like this. 
I don't know how the billions work, but 10 should be A-'aSaRa. , 8000000000 should be Tama:n'ijatu milja:Ra.:t , and please add a u after the t in 3000000000 up to 10000000000, so it should be Tal'a:Tatu, ?'aRbaAatu, etc. Hope you understand.

**Comment by sthibaul** [comment]
Also, please see the build failure:

```
Using phonemetable: 'ar'
Compiling: 'ar_listx'
	30089 entries
Compiling: 'ar_list'
  136: Bad phoneme [I] (U+49) in: _0  s[-'IfR
	251 entries
Compiling: 'ar_emoji'
	1639 entries
Compiling: 'ar_extra'
	0 entries
Compiling: 'ar_rules'
	383 rules, 39 groups (37)

Error: Compile error.
```

**Comment by king-dahmanus** [comment]
yup. Arabic doesn't have I, which is the i sound found in wip, hit or
flick. There's just i, and i., which is really not very cool

**Comment by sthibaul** [comment]
Please see the `make check` errors

**Pull request closed without merging**
