### PR TITLE
Readability fixes

### PR DESCRIPTION
**Pull request by jaacoppi**

### CODE REVIEW

**Comment by jaacoppi** [comment]
It seems i still have something to learn with git. I'll resolve the merge conflicts soon.

**Comment by rhdunn** [comment]
Don't worry about that -- I can handle the merge conflicts when merging the changes.

**Comment by jaacoppi** [comment]
Yeah, it seems me doing two things, S_2_TO_HEAVY and readability stuff  in the same file caused the file to be out of sync. Lesson learnt: don't do two things at the same time..

**Comment by rhdunn** [comment]
Done. Thanks for the fixes.

**Comment by rhdunn** [comment]
Not sure why GitHub thinks this hasn't been merged. I have merged and pushed the changes.

**Pull request closed without merging**
