### PR TITLE
add arabic voice (correction)

### PR DESCRIPTION
**Pull request by linuxscout**
Thanks for your comments, I fixed them, 
i correct the license text and remove mbrola binary file

### CODE REVIEW

**Comment by mohammad-suliman** [comment]
thanks much @linuxscout for this great work!!! 
any status update on this? many users will be interested in getting Arabic support with espeak, and I am one of them of course.
I wanted to start to work on this issue, but, luckily I saw this PR before I started.
thanks again, and waiting for a response from the devs
an, if there is something I can do to get this integrated faster in to espeak-ng, pleas let me know.

**Comment by linuxscout** [comment]
Salam,
We work on improving the voice quality, and embed eSpeak and test it with arabic support on android phones.
I have some new updates, I will upload it soon.  
In other hand, there is new project to support arabic in MaryTTS, 

please, view this http://morf.se:59125/ 
and follow https://github.com/HaraldBerthelsen/marytts-lang-ar

**Comment by rhdunn** [comment]
For me to merge this:

1.  the code should be rebased so that it does not have merge conflicts;
2.  the arabic MBROLA voice files should not be present in any requested commit (deleting them does not count);
3.  the license text should be corrected as part of the rebase/squash (i.e. it was affected by a search and replace for `A` with `aa`) so the text is valid on all merged commits, not just corrected afterwards;
4.  original author names should be preserved -- new authors can be added as separate lines.

Additionally, the commits:

1.  should be self-contained and complete -- adding missing files should be squashed into a single commit;
2.  should have a sensible description of what the commit is doing.

**Comment by linuxscout** [comment]
I will clean it, to do another pull request

**Comment by rhdunn** [comment]
Thanks.

**Comment by mohammad-suliman** [comment]
Thank you

**Pull request closed without merging**
