### PR TITLE
Fix Russian

### PR DESCRIPTION
**Pull request by Andiv06**
I fixed the problem with the pronunciation of number 1 and 8

### CODE REVIEW

**Comment by alex19EP** [comment]
I'm not sure if it's really better, but at least it's not a disaster.

**Comment by alex19EP** [comment]
I still don't like how 1 sounds, and besides, the tests haven't been updated.

**Comment by kirill-jjj** [comment]
@Andiv06, your fix's are really better than what was before, when I fixing Russian language I came to almost the same result. I hope you like what I do in Russian language in espeak

**Comment by kirill-jjj** [comment]
@Andiv06, but i used in 1 not o, but V#, bekoz it realy sounds strange  when I wright 21

**Pull request closed without merging**
