### PR TITLE
fix arabic

### PR DESCRIPTION
**Pull request by king-dahmanus**
fFirst step twards fixing the arabic pronunciation in Espeak ng. Please check the compatibility files within the ar_list file, and also the ar_listx if any phonemes are impossible to make

### CODE REVIEW

**Comment by valdisvi** [comment]
Thanks for contribution!
Note, that I made some fixes:
1. To pass tests: cded9518ab1bb9e3763352e1ce484cc4651392d1
2. To fix dictionary compilation error: dcb7ac33f557037a5d951a02305844eef7387f8a

**Comment by king-dahmanus** [comment]
I'm trying to test the changes with odo.lv/espeak, but I don't see the words I added/improved being pronounced as I made them. Is the version used there opsolete or something? Why doesn't it work?

**Comment by king-dahmanus** [comment]
Oh no! Looks like I fricked up things really bad! Those طs most of them are unnecessary, maybe my keyboard switched and I didn't realize it. I'll commit a fix later.

**Comment by king-dahmanus** [comment]
just opened another pr with the latest commit from my forc. Hope this one doesn't make things wrong

**Pull request merged**
