### PR TITLE
SSML cleanup

### PR DESCRIPTION
**Pull request by jaacoppi**
Move SSML related logic from ReadClause to ProcessSsmlTag and to a new function ParseSsmlReference().

Contributes to #369 and should make locating SSML bugs easier.

### CODE REVIEW

**Comment by valdisvi** [comment]
To check for regressions, I first cherry-picked only commit 959bf26 and run make check with everything else the same.
I got error:
```
testing tests/ssml/references.ssml2
1c1
< l'EsDan_: gr'eIt@D,an_: 'amp@s,and t'Ik_: kw'oUts
---
> gr'eIt@D,an_: l'EsDan_: gr'eIt@D,an_: 'amp@s,and t'Ik_: kw'oUts
make: *** [Makefile:2654: tests/ssml.check] Error 1
```
Does it means, that current implementation actually is broken and doesn't work as expected?
Why in `tests/ssml/references.ssml2`
```
<speak> &lt; &gt; &amp; &apos; &quot; </speak>
<speak> B &#66;</speak>
<speak>z &#x7A;</speak>
```
with all commits applied it works with spaces removed.

**Comment by jaacoppi** [comment]
I didn't even notice the test failing as it was added later.

Running this on current master branch:
`espeak-ng --punct -x -m -f input.txt` 
with input.txt being a simple one liner `<!-- Commenting --><speak>&apos;</speak>`
Produces: `gr'eIt@D,an_: t'Ik`. 

That is clearly wrong. It seems that the current way of handling combination of comments and entity references is broken somehow, and 34657e7 fixes it. My aim was to change nothing, just reorganize the code, so I certainly don't know why this is happening.



The extra spaces in references.ssml2 are there by accident. I can add a commit for reformatting. Is this good?
<speak>&lt; &gt; &amp; &apos; &quot;</speak>
<speak>B &#66;</speak>
<speak>z &#x7A;</speak>

**Comment by valdisvi** [comment]
I think, it is old problem which will be fixed, please add commit to make xml formatted nicer, and I'll merge it.
In future, it is better to start by adding test before refactoring. That will allow to ensure, that it either didn't come worse, or it actually fixes some problem which was not found before.

**Comment by jaacoppi** [comment]
Thanks, live and learn.. I was only testing with an ssml string before refactoring, but wrote the committed test with comments afterwards.

**Pull request merged**
