### PR TITLE
cs: Translate untranslated Czech emojis

### PR DESCRIPTION
**Pull request by michal-bida**
- Uncomment and translate untranslated Czech emojis

### CODE REVIEW

**Comment by michal-bida** [comment]
Hello, 
as my first contribution I translated and uncommented untranslated Czech emojis. I checked czech music notation and czech mathematical symbol guidelines. As it is my first attempt to contribute to github I find it very probable I messed something up - please do let me know, I will try to fix it.

**Comment by michal-bida** [comment]
I also managed to build and test it locally:

```
ESPEAK_DATA_PATH=`pwd` src/espeak-ng -v cs -X "*"
Found: '*' [hvjezJitSka]   $max3
hvj'ezJitSka
```

**Comment by michal-bida** [comment]
There is no maintainer for Czech language. My I kindly ask @jaacoppi or @djphoenix as two of recent contributors for review/guidelines? Thanks. :innocent:

**Comment by alex19EP** [comment]
thank you for contribution.

**Pull request merged**
