### PR TITLE
Improved detection and use of ronn and kramdown

### PR DESCRIPTION
**Pull request by danielbair**
Allows setting the path for ronn and kramdown

### CODE REVIEW

**Comment by valdisvi** [comment]
Thanks for proposal, but I wonder, for what case it would help.
Currently it doesn't change anything, except it adds unneeded complexity in `Makefile.am`.
If development environment doesn't know, what simple `ronn` and `kramdown` is, probably instead of patching `Makefile.am` it should be fixed in the environment at the first place.

**Comment by danielbair** [comment]
I am attempting to to add espeak-ng to MacPorts (and HomeBrew), and there isn't an unversioned ronn available. Also, kramdown is not detected by the configure script either. Without the patch, If I have the environment variable RONN set, the configure script detects this and adds RONN to the Makefile but the Makefile doesn't honor RONN being set, and it then errors out. I realize that this PR overrides the RONN in the Makefile that would be set by the configure script, but if the make args RONN and KRAMDOWN are passed, it builds without errors for both MacPorts and HomeBrew. I tried passing and alias for ronn to the MacPorts build environment, but it wasn't used.

**Comment by danielbair** [comment]
I found that RONN is being set by configure if detected or if already set by the environment.

**Comment by rhdunn** [comment]
Merged. Thanks!

**Pull request merged**
