### PR TITLE
Made the SpeechPlayer code C++, to make it more like the rest of the project

### PR DESCRIPTION
**Pull request by trypolis464**
A lot of ESpeak seems to be in C, not C++, so I went ahead and renamed these files, and also updated the makefile. I couldn't find any C++ specific functions, but I could've very well missed something.

### CODE REVIEW

**Comment by trypolis464** [comment]
Oh dear, my bad, it does at least have using namespace std;, but I'm not sure what from the std namespace it uses.

**Comment by trypolis464** [comment]
Okay yeah I must've been half awake or not checked frame. It uses classes, too. I'd recommend keeping this open though, I'll try to figure out... Something.

**Comment by trypolis464** [comment]
Okay so, what I'm thinking is, move all the properties of the Frame and SpeechWaveGenerator classes into structs, then for the methods, do something like void Frame_doAThing(Frame *theFrame, ...); Thoughts?

**Comment by trypolis464** [comment]
Another thing is that it uses std::queue, std::list, etc. Queue shouldn't be a huge problem, there might be a port of that to C, but not sure about list. I'll see what I can do, and might get another contributor behind this as well.

**Comment by alex19EP** [comment]
@trypolis464 hello. are you planning to return to this pr?

**Comment by alex19EP** [comment]
OK closing for now

**Pull request closed without merging**
